# Generated by Django 5.2.1 on 2025-05-09 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='api.area'),
        ),
        migrations.AlterField(
            model_name='areaservicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asignacionclienteusuario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='asignacionclienteusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='industria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='api.industria'),
        ),
        migrations.AlterField(
            model_name='industria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serviciocliente',
            name='moneda',
            field=models.CharField(choices=[('UF', 'UF'), ('USD', 'USD'), ('CLP', 'CLP')], default='CLP', max_length=10),
        ),
    ]
