# Generated by Django 5.2.1 on 2025-05-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_servicio_area_servicio_servicio_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
    ]
