# Generated by Django 5.2.1 on 2025-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usuario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bilingue',
            field=models.BooleanField(default=False, help_text='¿Este cliente requiere informes bilingües?'),
        ),
    ]
