# Generated by Django 5.2.1 on 2025-06-19 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='El supervisor asignado a este analista (debe ser de la misma área)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analistas_supervisados', to=settings.AUTH_USER_MODEL),
        ),
    ]
