# Generated by Django 5.2.1 on 2025-07-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_areas_to_cliente'),
        ('api', '0006_add_supervisor_relation'),
    ]

    operations = [
    ]
