# Generated by Django 5.2.1 on 2025-05-12 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_servicio_area_servicio_servicio_area_and_more'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('rut_auxiliar', models.CharField(db_column='rut_auxiliar', max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='nombre_auxiliar', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'db_table': 'contabilidad_auxiliar',
                'ordering': ['rut_auxiliar'],
            },
        ),
        migrations.AlterField(
            model_name='accountclassification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aperturacuenta',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cierremensual',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clasificacionoption',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clasificacionset',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='id',
            field=models.BigAutoField(db_column='id_cuenta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libromayorupload',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='auxiliar',
            field=models.ForeignKey(blank=True, db_column='auxiliar_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.auxiliar'),
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(db_column='id_centro_costo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'db_table': 'contabilidad_centrocosto',
                'ordering': ['nombre'],
                'unique_together': {('cliente', 'nombre')},
            },
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='centro_costo',
            field=models.ForeignKey(blank=True, db_column='centro_costo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto'),
        ),
    ]
