# Generated by Django 5.2.1 on 2025-05-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usuario_activo'),
        ('contabilidad', '0002_auxiliar_alter_accountclassification_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tipo_documento/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
    ]
