# Generated by Django 5.2.1 on 2025-05-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_libromayorupload_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierremensual',
            name='fecha_fin_libro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cierremensual',
            name='fecha_inicio_libro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
