# Generated by Django 5.2.1 on 2025-06-12 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('contabilidad', '0011_clasificacion_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkClasificacionUpload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='clasificaciones/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('subido', 'Archivo subido'), ('procesando', 'Procesando'), ('completado', 'Procesado correctamente'), ('error', 'Con errores')], default='subido', max_length=20)),
                ('errores', models.TextField(blank=True)),
                ('resumen', models.JSONField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
    ]
