# Generated by Django 5.2.1 on 2025-06-12 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('contabilidad', '0013_nombreseninglesupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_upload', models.CharField(choices=[('tipo_documento', 'Tipos de Documento'), ('clasificacion_bulk', 'Clasificación Bulk'), ('nombres_ingles', 'Nombres en Inglés'), ('libro_mayor', 'Libro Mayor')], max_length=20)),
                ('upload_id', models.PositiveIntegerField()),
                ('accion', models.CharField(choices=[('create', 'Creación'), ('reprocess', 'Reprocesamiento'), ('delete', 'Eliminación'), ('update', 'Actualización'), ('view', 'Visualización')], max_length=20)),
                ('descripcion', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Cambio en Upload',
                'verbose_name_plural': 'Logs de Cambios en Uploads',
                'ordering': ['-fecha'],
            },
        ),
    ]
