# Generated by Django 5.2.1 on 2025-06-13 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_uploadchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta', models.CharField(choices=[('tipo_documento', 'Tarjeta 1: Tipo de Documento'), ('libro_mayor', 'Tarjeta 2: Libro Mayor'), ('clasificacion', 'Tarjeta 3: Clasificaciones'), ('incidencias', 'Tarjeta 4: Incidencias'), ('revision', 'Tarjeta 5: Revisión')], max_length=20)),
                ('accion', models.CharField(choices=[('upload_excel', 'Subida de Excel'), ('manual_create', 'Creación Manual'), ('manual_edit', 'Edición Manual'), ('manual_delete', 'Eliminación Manual'), ('bulk_delete', 'Eliminación Masiva'), ('view_data', 'Visualización de Datos'), ('validation_error', 'Error de Validación'), ('process_start', 'Inicio de Procesamiento'), ('process_complete', 'Procesamiento Completado')], max_length=20)),
                ('descripcion', models.TextField()),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('exito', 'Exitoso'), ('error', 'Error'), ('warning', 'Advertencia')], default='exito', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='contabilidad.cierrecontabilidad')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Actividad de Tarjeta',
                'verbose_name_plural': 'Logs de Actividad de Tarjetas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cierre', 'tarjeta'], name='contabilida_cierre__18e218_idx'), models.Index(fields=['usuario', 'timestamp'], name='contabilida_usuario_301b73_idx')],
            },
        ),
    ]
