# Generated by Django 5.2.1 on 2025-06-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_tarjetaactivitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadChangeLog',
        ),
    ]
