# Generated by Django 5.2.1 on 2025-06-14 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('contabilidad', '0017_clasificacioncuentaarchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombresEnInglesArchivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('nombre_cuenta', models.CharField(blank=True, max_length=255)),
                ('nombre_ingles', models.CharField(max_length=255)),
                ('fila_excel', models.IntegerField()),
                ('procesado', models.BooleanField(default=False)),
                ('errores_mapeo', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('cuenta_mapeada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.cuentacontable')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres_archivo', to='contabilidad.nombreseninglesupload')),
            ],
            options={
                'verbose_name': 'Nombre en Inglés del Archivo',
                'verbose_name_plural': 'Nombres en Inglés del Archivo',
                'ordering': ['numero_cuenta'],
                'unique_together': {('upload', 'numero_cuenta')},
            },
        ),
    ]
