# Generated by Django 5.2.1 on 2025-06-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_upload_log_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlog',
            name='ruta_archivo',
            field=models.CharField(blank=True, help_text='Ruta relativa del archivo en storage', max_length=500),
        ),
    ]
