# Generated by Django 5.2.1 on 2025-06-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0026_alter_tarjetaactivitylog_tarjeta'),
        ('contabilidad', '0026_movimientocontable_flag_incompleto'),
    ]

    operations = [
    ]
