# Generated by Django 5.2.1 on 2025-07-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_supervisor_relation'),
        ('contabilidad', '0036_alter_historialreprocesamiento_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clasificacioncuentaarchivo',
            name='contabilida_cliente_0e6fb5_idx',
        ),
        migrations.RemoveIndex(
            model_name='clasificacioncuentaarchivo',
            name='contabilida_upload__c57733_idx',
        ),
        migrations.RemoveField(
            model_name='clasificacioncuentaarchivo',
            name='cuenta_mapeada',
        ),
        migrations.RemoveField(
            model_name='clasificacioncuentaarchivo',
            name='errores_mapeo',
        ),
        migrations.RemoveField(
            model_name='clasificacioncuentaarchivo',
            name='fecha_procesado',
        ),
        migrations.RemoveField(
            model_name='clasificacioncuentaarchivo',
            name='procesado',
        ),
        migrations.AddIndex(
            model_name='clasificacioncuentaarchivo',
            index=models.Index(fields=['cliente'], name='contabilida_cliente_0224da_idx'),
        ),
        migrations.AddIndex(
            model_name='clasificacioncuentaarchivo',
            index=models.Index(fields=['upload_log'], name='contabilida_upload__bdc228_idx'),
        ),
    ]
