# Generated by Django 5.2.1 on 2025-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0037_remove_clasificacioncuentaarchivo_contabilida_cliente_0e6fb5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciaresumen',
            name='accion_sugerida',
            field=models.TextField(blank=True, help_text='Acción sugerida para resolver la incidencia'),
        ),
        migrations.AddField(
            model_name='incidenciaresumen',
            name='mensaje_usuario',
            field=models.TextField(blank=True, help_text='Mensaje descriptivo para el usuario'),
        ),
    ]
