# Generated by Django 5.2.1 on 2025-07-02 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_supervisor_relation'),
        ('contabilidad', '0040_add_bilingual_fields_to_clasificacion_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacionoption',
            name='descripcion_en',
            field=models.TextField(blank=True, default='', help_text='Descripción en inglés para sets por defecto del sistema'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clasificacionoption',
            name='valor_en',
            field=models.CharField(blank=True, help_text='Valor en inglés para sets por defecto del sistema', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ExcepcionClasificacionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_codigo', models.CharField(help_text='Código de la cuenta', max_length=20)),
                ('motivo', models.TextField(blank=True, help_text='Motivo por el cual esta cuenta no aplica a este set específico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, help_text='Si está activa, la cuenta no será requerida en este set')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('set_clasificacion', models.ForeignKey(help_text='Set de clasificación al que NO aplica esta cuenta', on_delete=django.db.models.deletion.CASCADE, to='contabilidad.clasificacionset')),
                ('usuario_creador', models.ForeignKey(help_text='Usuario que creó la excepción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excepción de Clasificación por Set',
                'verbose_name_plural': 'Excepciones de Clasificación por Set',
                'indexes': [models.Index(fields=['cliente', 'set_clasificacion', 'activa'], name='contabilida_cliente_273e76_idx'), models.Index(fields=['cuenta_codigo', 'activa'], name='contabilida_cuenta__5097bc_idx')],
                'unique_together': {('cliente', 'cuenta_codigo', 'set_clasificacion')},
            },
        ),
    ]
