# Generated by Django 5.2.1 on 2025-07-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0041_agregar_excepcion_clasificacion_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetaactivitylog',
            name='accion',
            field=models.CharField(choices=[('upload_excel', 'Subida de Excel'), ('manual_create', 'Creación Manual'), ('manual_edit', 'Edición Manual'), ('manual_delete', 'Eliminación Manual'), ('bulk_delete', 'Eliminación Masiva'), ('view_data', 'Visualización de Datos'), ('view_list', 'Visualización de Lista'), ('validation_error', 'Error de Validación'), ('process_start', 'Inicio de Procesamiento'), ('process_complete', 'Procesamiento Completado'), ('set_create', 'Creación de Set'), ('set_edit', 'Edición de Set'), ('set_delete', 'Eliminación de Set'), ('option_create', 'Creación de Opción'), ('option_edit', 'Edición de Opción'), ('option_delete', 'Eliminación de Opción'), ('individual_create', 'Creación Individual'), ('individual_edit', 'Edición Individual'), ('individual_delete', 'Eliminación Individual'), ('delete_all', 'Eliminación Total')], max_length=25),
        ),
    ]
