# Generated by Django 5.2.1 on 2025-07-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0043_add_set_clasificacion_to_incidencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecontabilidad',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se finalizó el cierre y se generaron reportes', null=True),
        ),
        migrations.AddField(
            model_name='cierrecontabilidad',
            name='fecha_sin_incidencias',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando el cierre quedó sin incidencias pendientes', null=True),
        ),
        migrations.AddField(
            model_name='cierrecontabilidad',
            name='reportes_generados',
            field=models.BooleanField(default=False, help_text='Indica si se han generado los reportes finales'),
        ),
        migrations.AlterField(
            model_name='cierrecontabilidad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('clasificacion', 'Esperando Clasificación'), ('incidencias', 'Incidencias Abiertas'), ('sin_incidencias', 'Sin Incidencias'), ('generando_reportes', 'Generando Reportes'), ('en_revision', 'En Revisión'), ('rechazado', 'Rechazado'), ('aprobado', 'Aprobado'), ('finalizado', 'Finalizado'), ('completo', 'Completo')], default='pendiente', max_length=30),
        ),
    ]
