# Generated by Django 5.2.1 on 2025-07-09 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_supervisor_relation'),
        ('contabilidad', '0046_alter_incidencia_tipo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clasificacioncuentaarchivo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='archivo_origen',
            field=models.ForeignKey(blank=True, help_text='Registro origen en ClasificacionCuentaArchivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.clasificacioncuentaarchivo'),
        ),
        migrations.AddField(
            model_name='clasificacioncuentaarchivo',
            name='activo',
            field=models.BooleanField(default=True, help_text='False si este registro fue reemplazado por una nueva versión'),
        ),
        migrations.AddField(
            model_name='clasificacioncuentaarchivo',
            name='fecha_obsolescencia',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando este registro se marcó como obsoleto', null=True),
        ),
        migrations.AddIndex(
            model_name='clasificacioncuentaarchivo',
            index=models.Index(fields=['activo'], name='contabilida_activo_9406c5_idx'),
        ),
        migrations.AddIndex(
            model_name='clasificacioncuentaarchivo',
            index=models.Index(fields=['cliente', 'activo'], name='contabilida_cliente_fbf58f_idx'),
        ),
    ]
