# Generated by Django 5.2.1 on 2025-07-10 21:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_supervisor_relation'),
        ('contabilidad', '0047_alter_clasificacioncuentaarchivo_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificacioncuentaarchivo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='clasificacioncuentaarchivo',
            name='upload_log',
        ),
        migrations.AlterUniqueTogether(
            name='accountclassification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='cliente',
            field=models.ForeignKey(default=2, help_text='Cliente de la clasificación (extraído de cuenta o explícito)', on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='cuenta_codigo',
            field=models.CharField(blank=True, help_text='Código de cuenta temporal cuando la cuenta no existe aún', max_length=50),
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización del registro'),
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creación del registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='origen',
            field=models.CharField(choices=[('excel', 'Archivo Excel'), ('manual', 'Creación Manual'), ('migracion', 'Migración de Temporal a FK'), ('actualizacion', 'Actualización desde Excel')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='upload_log',
            field=models.ForeignKey(blank=True, help_text='Upload que originó esta clasificación (si viene de Excel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.uploadlog'),
        ),
        migrations.AlterField(
            model_name='accountclassification',
            name='cuenta',
            field=models.ForeignKey(blank=True, help_text='Cuenta existente (preferido). Si es NULL, usar cuenta_codigo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='contabilidad.cuentacontable'),
        ),
        migrations.AddIndex(
            model_name='accountclassification',
            index=models.Index(fields=['cliente', 'cuenta_codigo'], name='contabilida_cliente_73dd80_idx'),
        ),
        migrations.AddIndex(
            model_name='accountclassification',
            index=models.Index(fields=['cuenta'], name='contabilida_cuenta__068b07_idx'),
        ),
        migrations.AddIndex(
            model_name='accountclassification',
            index=models.Index(fields=['upload_log'], name='contabilida_upload__8b942b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountclassification',
            index=models.Index(fields=['origen', 'fecha_creacion'], name='contabilida_origen_b41bd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountclassification',
            constraint=models.UniqueConstraint(condition=models.Q(('cuenta__isnull', False)), fields=('cuenta', 'set_clas'), name='unique_cuenta_set_when_cuenta_exists'),
        ),
        migrations.AddConstraint(
            model_name='accountclassification',
            constraint=models.UniqueConstraint(condition=models.Q(('cuenta__isnull', True)), fields=('cliente', 'cuenta_codigo', 'set_clas'), name='unique_cliente_codigo_set_when_cuenta_null'),
        ),
        migrations.AddConstraint(
            model_name='accountclassification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cuenta__isnull', False), ('cuenta_codigo', '')), models.Q(('cuenta__isnull', True), ('cuenta_codigo__isnull', False)), _connector='OR'), name='cuenta_or_codigo_required'),
        ),
        migrations.RemoveField(
            model_name='accountclassification',
            name='archivo_origen',
        ),
        migrations.DeleteModel(
            name='ClasificacionCuentaArchivo',
        ),
    ]
