# Generated by Django 5.2.1 on 2025-07-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0049_remove_accountclassification_cuenta_or_codigo_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacionoption',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Descripción en inglés - disponible para todas las opciones'),
        ),
        migrations.AlterField(
            model_name='clasificacionoption',
            name='valor_en',
            field=models.CharField(blank=True, help_text='Valor en inglés - disponible para todas las opciones', max_length=100, null=True),
        ),
    ]
