# Generated by Django 5.2.1 on 2025-07-20 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0007_merge_20250717_2256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheConsultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_cache', models.CharField(db_index=True, help_text='Clave única del cache (hash MD5 de la consulta)', max_length=128, unique=True)),
                ('consulta_tipo', models.CharField(db_index=True, help_text='Tipo de consulta cacheada', max_length=50)),
                ('parametros_consulta', models.JSONField(help_text='Parámetros originales de la consulta')),
                ('cliente_id', models.PositiveIntegerField(db_index=True, help_text='Cliente asociado al cache')),
                ('periodo', models.CharField(db_index=True, help_text='Período asociado al cache', max_length=7)),
                ('resultado_comprimido', models.BinaryField(help_text='Resultado de la consulta comprimido con gzip')),
                ('tamaño_original', models.PositiveIntegerField(help_text='Tamaño original del resultado en bytes')),
                ('tamaño_comprimido', models.PositiveIntegerField(help_text='Tamaño comprimido del resultado en bytes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(db_index=True, help_text='Fecha de expiración del cache')),
                ('ttl_segundos', models.PositiveIntegerField(help_text='Time To Live original en segundos')),
                ('hits', models.PositiveIntegerField(default=0, help_text='Número de veces que se usó este cache')),
                ('ultima_lectura', models.DateTimeField(blank=True, help_text='Última vez que se leyó este cache', null=True)),
                ('dependencias', models.JSONField(default=list, help_text='Lista de entidades que invalidan este cache')),
                ('version_datos', models.CharField(help_text='Hash de los datos de los cuales depende el cache', max_length=32)),
            ],
            options={
                'verbose_name': 'Cache de Consulta',
                'verbose_name_plural': 'Caches de Consultas',
                'ordering': ['-ultima_lectura'],
                'indexes': [models.Index(fields=['consulta_tipo', 'cliente_id', 'periodo'], name='nomina_cach_consult_58d056_idx'), models.Index(fields=['fecha_expiracion'], name='nomina_cach_fecha_e_7d212b_idx'), models.Index(fields=['hits', 'ultima_lectura'], name='nomina_cach_hits_2fa3a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CierreNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: YYYY-MM (ej: 2025-07)', max_length=7)),
                ('estado', models.CharField(choices=[('iniciado', 'Cierre Iniciado'), ('en_redis', 'En Proceso de Validación (Redis)'), ('validado', 'Validado Sin Discrepancias'), ('con_discrepancias', 'Con Discrepancias Pendientes'), ('consolidado', 'Consolidado en Base de Datos'), ('cerrado', 'Cerrado Definitivamente'), ('error', 'Error en Proceso'), ('reabierto', 'Cierre Reabierto')], default='iniciado', help_text='Estado actual del proceso de cierre', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_consolidacion', models.DateTimeField(blank=True, help_text='Fecha cuando se consolidaron los datos desde Redis', null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha cuando se cerró definitivamente', null=True)),
                ('discrepancias_detectadas', models.PositiveIntegerField(default=0, help_text='Número de discrepancias detectadas en validación Redis')),
                ('cache_key_redis', models.CharField(blank=True, help_text='Clave base en Redis para este cierre', max_length=200, null=True)),
                ('archivos_procesados', models.JSONField(blank=True, default=dict, help_text='Resumen de archivos subidos y procesados')),
                ('total_empleados_activos', models.PositiveIntegerField(default=0, help_text='Total de empleados activos en el período')),
                ('total_finiquitos', models.PositiveIntegerField(default=0, help_text='Total de finiquitos en el período')),
                ('total_ingresos', models.PositiveIntegerField(default=0, help_text='Total de ingresos en el período')),
                ('fecha_reapertura', models.DateTimeField(blank=True, help_text='Fecha de reapertura si aplica', null=True)),
                ('motivo_reapertura', models.TextField(blank=True, help_text='Motivo de la reapertura')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión del cierre (incrementa con reaperturas)')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del proceso de cierre')),
                ('analista_responsable', models.ForeignKey(blank=True, help_text='Analista responsable del cierre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_asignados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario_cierre', models.ForeignKey(blank=True, help_text='Usuario que ejecutó el cierre final', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_ejecutados', to=settings.AUTH_USER_MODEL)),
                ('usuario_reapertura', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la reapertura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaperturas_ejecutadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Nómina',
                'verbose_name_plural': 'Cierres de Nómina',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ausentismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empleado', models.CharField(db_index=True, max_length=12)),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('tipo_ausentismo', models.CharField(help_text='Tipo de ausentismo (vacaciones, licencia médica, etc.)', max_length=50)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del ausentismo')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del ausentismo')),
                ('dias_ausentismo', models.PositiveIntegerField(default=0, help_text='Número de días de ausentismo')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del ausentismo')),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.ForeignKey(help_text='Cierre al que pertenece este ausentismo', on_delete=django.db.models.deletion.CASCADE, related_name='ausentismos', to='nomina.cierrenomina')),
            ],
            options={
                'verbose_name': 'Ausentismo',
                'verbose_name_plural': 'Ausentismos',
                'ordering': ['fecha_inicio', 'nombre_empleado'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empleado', models.CharField(db_index=True, max_length=12)),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('tipo_empleado', models.CharField(choices=[('activo', 'Empleado Activo'), ('finiquito', 'Finiquito'), ('ingreso', 'Ingreso')], default='activo', help_text='Tipo de empleado en este período', max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, help_text="Fecha de ingreso (para tipo 'ingreso')", null=True)),
                ('fecha_finiquito', models.DateField(blank=True, help_text="Fecha de finiquito (para tipo 'finiquito')", null=True)),
                ('motivo_finiquito', models.CharField(blank=True, help_text='Motivo del finiquito', max_length=200)),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.ForeignKey(help_text='Cierre al que pertenece este empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleados_nomina', to='nomina.cierrenomina')),
            ],
            options={
                'verbose_name': 'Empleado Nómina',
                'verbose_name_plural': 'Empleados Nómina',
                'ordering': ['nombre_empleado'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Nombre del concepto tal como viene de Talana', max_length=200)),
                ('valor', models.CharField(help_text='Valor como texto (puede ser numérico o descriptivo)', max_length=255)),
                ('valor_numerico', models.DecimalField(decimal_places=2, default=0, help_text='Valor numérico para cálculos (0 si no es numérico)', max_digits=15)),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
                ('empleado_nomina', models.ForeignKey(help_text='Empleado al que pertenece este concepto', on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='nomina.empleadonomina')),
            ],
            options={
                'verbose_name': 'Concepto de Empleado',
                'verbose_name_plural': 'Conceptos de Empleados',
                'ordering': ['concepto'],
            },
        ),
        migrations.CreateModel(
            name='ComparacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comparacion', models.CharField(choices=[('empleado_continuo', 'Empleado Continuo'), ('empleado_nuevo', 'Empleado Nuevo'), ('empleado_saliente', 'Empleado Saliente'), ('empleado_reingreso', 'Empleado Reingreso')], db_index=True, help_text='Tipo de comparación según situación del empleado', max_length=20)),
                ('variacion_sueldo_base', models.DecimalField(decimal_places=2, default=0, help_text='Variación absoluta del sueldo base', max_digits=15)),
                ('variacion_sueldo_porcentual', models.DecimalField(decimal_places=4, default=0, help_text='Variación porcentual del sueldo base', max_digits=8)),
                ('variacion_total_haberes', models.DecimalField(decimal_places=2, default=0, help_text='Variación absoluta total de haberes', max_digits=15)),
                ('variacion_total_haberes_porcentual', models.DecimalField(decimal_places=4, default=0, help_text='Variación porcentual total de haberes', max_digits=8)),
                ('nivel_anomalia', models.CharField(choices=[('no', 'Variación Normal'), ('menor', 'Anomalía Menor (<20% variación)'), ('mayor', 'Anomalía Mayor (20-50% variación)'), ('critica', 'Anomalía Crítica (>50% variación)')], db_index=True, default='no', help_text='Nivel de anomalía detectado automáticamente', max_length=10)),
                ('detalle_variaciones', models.JSONField(default=dict, help_text='Detalle de variaciones por cada concepto')),
                ('tendencia_3_meses', models.CharField(blank=True, help_text='Tendencia calculada de 3 meses (ascendente/descendente/estable)', max_length=20)),
                ('coeficiente_variacion', models.DecimalField(decimal_places=6, default=0, help_text='Coeficiente de variación para estabilidad salarial', max_digits=8)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('algoritmo_version', models.CharField(default='v2.0', help_text='Versión del algoritmo de comparación', max_length=10)),
                ('cierre_actual', models.ForeignKey(help_text='Cierre del período actual', on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_como_actual', to='nomina.cierrenomina')),
                ('cierre_anterior', models.ForeignKey(help_text='Cierre del período anterior', on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_como_anterior', to='nomina.cierrenomina')),
                ('empleado_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_actuales', to='nomina.empleadonomina')),
                ('empleado_anterior', models.ForeignKey(blank=True, help_text='Puede ser null si el empleado es nuevo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_anteriores', to='nomina.empleadonomina')),
            ],
            options={
                'verbose_name': 'Comparación Mensual',
                'verbose_name_plural': 'Comparaciones Mensuales',
                'ordering': ['-variacion_sueldo_porcentual'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoOfuscado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_hash', models.CharField(db_index=True, help_text='Hash SHA-256 del RUT para identificación anónima', max_length=64)),
                ('nombre_ofuscado', models.CharField(help_text='Nombre ofuscado pero reversible', max_length=200)),
                ('tipo_empleado', models.CharField(choices=[('activo', 'Empleado Activo'), ('finiquito', 'Finiquito'), ('ingreso', 'Ingreso')], help_text='Tipo de empleado (no sensible)', max_length=20)),
                ('rango_salarial', models.CharField(help_text='Rango salarial en lugar de valor exacto', max_length=20)),
                ('salt_ofuscacion', models.CharField(help_text='Salt único para este registro', max_length=32)),
                ('algoritmo_version', models.CharField(default='v1.0', help_text='Versión del algoritmo de ofuscación', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('accesos_datos_reales', models.PositiveIntegerField(default=0, help_text='Contador de accesos a datos reales')),
                ('ultimo_acceso_real', models.DateTimeField(blank=True, help_text='Última vez que se accedieron los datos reales', null=True)),
                ('cierre', models.ForeignKey(help_text='Cierre al que pertenece este empleado ofuscado', on_delete=django.db.models.deletion.CASCADE, related_name='empleados_ofuscados', to='nomina.cierrenomina')),
            ],
            options={
                'verbose_name': 'Empleado Ofuscado',
                'verbose_name_plural': 'Empleados Ofuscados',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora cuando se detectó la incidencia')),
                ('empleado_rut', models.CharField(db_index=True, max_length=12)),
                ('empleado_nombre', models.CharField(max_length=200)),
                ('concepto_afectado', models.CharField(max_length=200)),
                ('valor_periodo_anterior', models.DecimalField(blank=True, decimal_places=2, help_text='Valor del mismo concepto en el período anterior', max_digits=15, null=True)),
                ('valor_periodo_actual', models.DecimalField(decimal_places=2, help_text='Valor del concepto en el período actual', max_digits=15)),
                ('diferencia_absoluta', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia absoluta entre períodos', max_digits=15)),
                ('diferencia_porcentual', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia porcentual entre períodos', max_digits=5)),
                ('tipo_incidencia', models.CharField(choices=[('variacion_sospechosa', 'Variación Sospechosa'), ('empleado_nuevo', 'Empleado Nuevo'), ('empleado_saliente', 'Empleado Saliente'), ('concepto_nuevo', 'Concepto Nuevo'), ('valor_extremo', 'Valor Extremo'), ('otro', 'Otro')], help_text='Tipo de incidencia detectada', max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('en_revision', 'En Revisión por Analista'), ('escalada', 'Escalada a Supervisor'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada')], default='pendiente', help_text='Estado actual de la incidencia', max_length=20)),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Fecha de resolución de la incidencia', null=True)),
                ('observaciones_resolucion', models.TextField(blank=True, help_text='Observaciones de la resolución')),
                ('analista_asignado', models.ForeignKey(blank=True, help_text='Analista asignado para revisar la incidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(help_text='Cierre donde se detectó la incidencia', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='nomina.cierrenomina')),
                ('supervisor_asignado', models.ForeignKey(blank=True, help_text='Supervisor asignado para revisar la incidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_supervisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_resolucion', models.ForeignKey(blank=True, help_text='Usuario que resolvió la incidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='IndiceEmpleadoBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_normalizado', models.CharField(db_index=True, help_text='Texto normalizado para búsqueda exacta', max_length=400)),
                ('rut_normalizado', models.CharField(db_index=True, help_text='RUT sin puntos ni guiones', max_length=15)),
                ('soundex_nombre', models.CharField(db_index=True, help_text='Código Soundex para búsqueda fonética', max_length=10)),
                ('periodo_activo', models.CharField(db_index=True, help_text='Período donde está activo (YYYY-MM)', max_length=7)),
                ('cliente_id', models.PositiveIntegerField(db_index=True, help_text='ID del cliente para filtros rápidos')),
                ('rango_salarial_codigo', models.CharField(db_index=True, help_text='Código del rango salarial (A, B, C, D, E)', max_length=5)),
                ('total_conceptos', models.PositiveIntegerField(default=0, help_text='Número total de conceptos del empleado')),
                ('suma_haberes_imponibles', models.DecimalField(decimal_places=2, default=0, help_text='Suma de haberes imponibles pre-calculada', max_digits=15)),
                ('fecha_indexacion', models.DateTimeField(auto_now=True)),
                ('version_indice', models.CharField(default='v1.0', help_text='Versión del algoritmo de indexación', max_length=10)),
                ('empleado_nomina', models.OneToOneField(help_text='Empleado indexado para búsqueda', on_delete=django.db.models.deletion.CASCADE, related_name='indice_busqueda', to='nomina.empleadonomina')),
            ],
            options={
                'verbose_name': 'Índice de Búsqueda Empleado',
                'verbose_name_plural': 'Índices de Búsqueda Empleados',
            },
        ),
        migrations.CreateModel(
            name='InteraccionIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_interaccion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(help_text='Mensaje de la interacción')),
                ('tipo_interaccion', models.CharField(choices=[('comentario', 'Comentario'), ('pregunta', 'Pregunta'), ('respuesta', 'Respuesta'), ('escalacion', 'Escalación'), ('resolucion', 'Resolución')], default='comentario', help_text='Tipo de interacción', max_length=20)),
                ('incidencia', models.ForeignKey(help_text='Incidencia a la que pertenece esta interacción', on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='nomina.incidencia')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la interacción', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción de Incidencia',
                'verbose_name_plural': 'Interacciones de Incidencias',
                'ordering': ['fecha_interaccion'],
            },
        ),
        migrations.CreateModel(
            name='KPINomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_kpi', models.CharField(choices=[('total_haberes_imponibles', 'Total Haberes Imponibles'), ('total_haberes_no_imponibles', 'Total Haberes No Imponibles'), ('total_descuentos_legales', 'Total Descuentos Legales'), ('total_otros_descuentos', 'Total Otros Descuentos'), ('total_aportes_patronales', 'Total Aportes Patronales'), ('total_horas_extras', 'Total Horas Extras'), ('promedio_sueldo_base', 'Promedio Sueldo Base'), ('empleados_activos_count', 'Cantidad Empleados Activos'), ('empleados_finiquitos_count', 'Cantidad Finiquitos'), ('empleados_ingresos_count', 'Cantidad Ingresos'), ('masa_salarial_total', 'Masa Salarial Total'), ('variacion_vs_anterior', 'Variación vs Período Anterior')], db_index=True, help_text='Tipo de KPI para búsquedas optimizadas', max_length=40)),
                ('valor_numerico', models.DecimalField(decimal_places=2, help_text='Valor principal del KPI', max_digits=20)),
                ('valor_comparativo_anterior', models.DecimalField(blank=True, decimal_places=2, help_text='Valor del período anterior para comparación', max_digits=20, null=True)),
                ('variacion_porcentual', models.DecimalField(decimal_places=4, default=0, help_text='Variación porcentual respecto período anterior', max_digits=8)),
                ('metadatos_kpi', models.JSONField(default=dict, help_text='Metadatos adicionales del KPI (distribuciones, percentiles, etc.)')),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('hash_verificacion', models.CharField(help_text='Hash para verificar integridad del KPI', max_length=64)),
                ('cierre', models.ForeignKey(help_text='Cierre al que pertenece este KPI', on_delete=django.db.models.deletion.CASCADE, related_name='kpis_calculados', to='nomina.cierrenomina')),
            ],
            options={
                'verbose_name': 'KPI de Nómina',
                'verbose_name_plural': 'KPIs de Nómina',
                'ordering': ['tipo_kpi'],
            },
        ),
        migrations.CreateModel(
            name='LogAccesoOfuscacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('motivo_acceso', models.CharField(max_length=200)),
                ('ip_acceso', models.GenericIPAddressField(blank=True, null=True)),
                ('empleado_ofuscado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acceso', to='nomina.empleadoofuscado')),
                ('usuario_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Acceso Ofuscación',
                'verbose_name_plural': 'Logs Acceso Ofuscación',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.CreateModel(
            name='LogArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('libro_remuneraciones', 'Libro de Remuneraciones'), ('novedades', 'Novedades'), ('movimientos_mes', 'Movimientos del Mes'), ('analista', 'Archivo del Analista')], max_length=30)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_temporal', models.CharField(help_text='Ruta donde se guardó temporalmente el archivo', max_length=500)),
                ('estado', models.CharField(choices=[('subido', 'Archivo Subido'), ('procesando', 'Procesando en Redis'), ('procesado', 'Procesado Exitosamente'), ('error', 'Error en Procesamiento')], default='subido', max_length=20)),
                ('tamaño_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_registros', models.PositiveIntegerField(default=0, help_text='Total de registros/filas procesadas')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('cierre', models.ForeignKey(help_text='Cierre al que pertenecen estos archivos', on_delete=django.db.models.deletion.CASCADE, related_name='logs_archivos', to='nomina.cierrenomina')),
                ('usuario_subida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Archivo',
                'verbose_name_plural': 'Logs de Archivos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='MapeoConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_original', models.CharField(help_text='Concepto tal como aparece en el libro de remuneraciones', max_length=200)),
                ('concepto_estandar', models.CharField(help_text='Código estándar del concepto (ej: SUELDO_BASE)', max_length=100)),
                ('clasificacion', models.CharField(choices=[('haber_imponible', 'Haber Imponible'), ('haber_no_imponible', 'Haber No Imponible'), ('horas_extras', 'Horas Extras'), ('descuento_legal', 'Descuento Legal'), ('otro_descuento', 'Otro Descuento'), ('aporte_patronal', 'Aporte Patronal'), ('informativo', 'Solo Informativo'), ('impuesto', 'Impuesto')], help_text='Clasificación contable del concepto', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_numerico', models.BooleanField(default=True, help_text='Si el concepto tiene valor numérico')),
                ('orden_display', models.PositiveIntegerField(default=0, help_text='Orden para mostrar en reportes')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario_mapea', models.ForeignKey(blank=True, help_text='Usuario que creó este mapeo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapeo de Concepto',
                'verbose_name_plural': 'Mapeos de Conceptos',
                'ordering': ['orden_display', 'concepto_estandar'],
            },
        ),
        migrations.CreateModel(
            name='MapeoNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_novedades', models.CharField(help_text='Concepto tal como aparece en el archivo de novedades', max_length=200)),
                ('concepto_libro', models.CharField(help_text='Concepto del libro al que mapea (debe existir en MapeoConcepto)', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario_mapea', models.ForeignKey(blank=True, help_text='Usuario que creó este mapeo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapeo de Novedades',
                'verbose_name_plural': 'Mapeos de Novedades',
                'ordering': ['concepto_novedades'],
            },
        ),
        migrations.AddIndex(
            model_name='cierrenomina',
            index=models.Index(fields=['cliente', 'periodo'], name='nomina_cier_cliente_b223b6_idx'),
        ),
        migrations.AddIndex(
            model_name='cierrenomina',
            index=models.Index(fields=['estado'], name='nomina_cier_estado_e4dfab_idx'),
        ),
        migrations.AddIndex(
            model_name='cierrenomina',
            index=models.Index(fields=['fecha_creacion'], name='nomina_cier_fecha_c_a716c5_idx'),
        ),
        migrations.AddIndex(
            model_name='cierrenomina',
            index=models.Index(fields=['analista_responsable'], name='nomina_cier_analist_aad393_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cierrenomina',
            unique_together={('cliente', 'periodo')},
        ),
        migrations.AddIndex(
            model_name='ausentismo',
            index=models.Index(fields=['cierre', 'rut_empleado'], name='nomina_ause_cierre__eae26b_idx'),
        ),
        migrations.AddIndex(
            model_name='ausentismo',
            index=models.Index(fields=['tipo_ausentismo'], name='nomina_ause_tipo_au_0d3802_idx'),
        ),
        migrations.AddIndex(
            model_name='ausentismo',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='nomina_ause_fecha_i_d16217_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadonomina',
            index=models.Index(fields=['cierre', 'rut_empleado'], name='nomina_empl_cierre__cfd546_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadonomina',
            index=models.Index(fields=['tipo_empleado'], name='nomina_empl_tipo_em_917daa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empleadonomina',
            unique_together={('cierre', 'rut_empleado')},
        ),
        migrations.AddIndex(
            model_name='empleadoconcepto',
            index=models.Index(fields=['empleado_nomina'], name='nomina_empl_emplead_b28d30_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadoconcepto',
            index=models.Index(fields=['concepto'], name='nomina_empl_concept_b2f492_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadoconcepto',
            index=models.Index(fields=['valor_numerico'], name='nomina_empl_valor_n_2913b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empleadoconcepto',
            unique_together={('empleado_nomina', 'concepto')},
        ),
        migrations.AddIndex(
            model_name='comparacionmensual',
            index=models.Index(fields=['cierre_actual', 'empleado_actual'], name='nomina_comp_cierre__76a20d_idx'),
        ),
        migrations.AddIndex(
            model_name='comparacionmensual',
            index=models.Index(fields=['nivel_anomalia', 'variacion_sueldo_porcentual'], name='nomina_comp_nivel_a_63131f_idx'),
        ),
        migrations.AddIndex(
            model_name='comparacionmensual',
            index=models.Index(fields=['tendencia_3_meses', 'coeficiente_variacion'], name='nomina_comp_tendenc_9e7b0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comparacionmensual',
            unique_together={('cierre_actual', 'empleado_actual')},
        ),
        migrations.AddIndex(
            model_name='empleadoofuscado',
            index=models.Index(fields=['rut_hash'], name='nomina_empl_rut_has_7fddd1_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadoofuscado',
            index=models.Index(fields=['cierre', 'tipo_empleado'], name='nomina_empl_cierre__0ca323_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadoofuscado',
            index=models.Index(fields=['rango_salarial'], name='nomina_empl_rango_s_770323_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empleadoofuscado',
            unique_together={('cierre', 'rut_hash')},
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['cierre', 'empleado_rut'], name='nomina_inci_cierre__362f08_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['tipo_incidencia'], name='nomina_inci_tipo_in_ebf38f_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['estado'], name='nomina_inci_estado_ddda50_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_deteccion'], name='nomina_inci_fecha_d_22aedf_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['analista_asignado'], name='nomina_inci_analist_f17910_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['supervisor_asignado'], name='nomina_inci_supervi_930041_idx'),
        ),
        migrations.AddIndex(
            model_name='indiceempleadobusqueda',
            index=models.Index(fields=['cliente_id', 'periodo_activo', 'rango_salarial_codigo'], name='nomina_indi_cliente_a708ae_idx'),
        ),
        migrations.AddIndex(
            model_name='indiceempleadobusqueda',
            index=models.Index(fields=['soundex_nombre'], name='nomina_indi_soundex_ab9d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='indiceempleadobusqueda',
            index=models.Index(fields=['suma_haberes_imponibles'], name='nomina_indi_suma_ha_fb6b14_idx'),
        ),
        migrations.AddIndex(
            model_name='interaccionincidencia',
            index=models.Index(fields=['incidencia', 'fecha_interaccion'], name='nomina_inte_inciden_dd7d86_idx'),
        ),
        migrations.AddIndex(
            model_name='interaccionincidencia',
            index=models.Index(fields=['usuario'], name='nomina_inte_usuario_7338ad_idx'),
        ),
        migrations.AddIndex(
            model_name='kpinomina',
            index=models.Index(fields=['cierre', 'tipo_kpi'], name='nomina_kpin_cierre__45668e_idx'),
        ),
        migrations.AddIndex(
            model_name='kpinomina',
            index=models.Index(fields=['tipo_kpi', 'fecha_calculo'], name='nomina_kpin_tipo_kp_ae49dd_idx'),
        ),
        migrations.AddIndex(
            model_name='kpinomina',
            index=models.Index(fields=['variacion_porcentual'], name='nomina_kpin_variaci_4ad044_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpinomina',
            unique_together={('cierre', 'tipo_kpi')},
        ),
        migrations.AddIndex(
            model_name='logarchivo',
            index=models.Index(fields=['cierre', 'tipo_archivo'], name='nomina_loga_cierre__28a0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='logarchivo',
            index=models.Index(fields=['estado'], name='nomina_loga_estado_7dadb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mapeoconcepto',
            unique_together={('cliente', 'concepto_original')},
        ),
        migrations.AlterUniqueTogether(
            name='mapeonovedades',
            unique_together={('cliente', 'concepto_novedades')},
        ),
    ]
