# Generated by Django 5.2.1 on 2025-06-06 02:46

import django.db.models.deletion
import nomina.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('datos_consolidados', 'Datos Consolidados'), ('reportes_generados', 'Reportes Generados'), ('validacion_senior', 'Validación Senior'), ('completado', 'Completado')], default='pendiente', max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario_analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_analista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cliente', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('no_realizado', 'No Realizado')], default='pendiente', max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoNovedadesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=nomina.models.novedades_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('procesado', 'Procesado'), ('con_error', 'Con Error')], default='pendiente', max_length=20)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_novedades', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAnalistaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('ingresos', 'Ingresos'), ('finiquitos', 'Finiquitos'), ('ausentismos', 'Ausentismos')], max_length=20)),
                ('archivo', models.FileField(upload_to=nomina.models.analista_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('procesado', 'Procesado'), ('con_error', 'Con Error')], default='pendiente', max_length=20)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_analista', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoRemuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concepto', models.CharField(max_length=120)),
                ('clasificacion', models.CharField(choices=[('haber', 'Haber'), ('descuento', 'Descuento'), ('informacion', 'Información')], max_length=20)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('vigente', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'nombre_concepto')},
            },
        ),
        migrations.CreateModel(
            name='EmpleadoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido_paterno', models.CharField(max_length=120)),
                ('apellido_materno', models.CharField(blank=True, max_length=120)),
                ('rut_empresa', models.CharField(max_length=20)),
                ('dias_trabajados', models.IntegerField(blank=True, null=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='nomina.cierrenomina')),
            ],
            options={
                'unique_together': {('cierre', 'rut')},
            },
        ),
        migrations.CreateModel(
            name='LibroRemuneracionesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=nomina.models.libro_remuneraciones_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('analizando_hdrs', 'Analizando Headers'), ('hdrs_analizados', 'Headers Analizados'), ('clasif_en_proceso', 'Clasificación en Proceso'), ('clasif_pendiente', 'Clasificación Pendiente'), ('clasificado', 'Clasificado'), ('con_error', 'Con Error')], default='pendiente', max_length=60)),
                ('header_json', models.JSONField(default=list)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_remuneraciones', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoAusentismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_ausentismo', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.IntegerField()),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoFiniquito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_finiquito', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=120, null=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_ingreso', models.DateField()),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientosMesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=nomina.models.movimientos_mes_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('procesado', 'Procesado'), ('con_error', 'Con Error')], default='pendiente', max_length=20)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_mes', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroConceptoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concepto_original', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.conceptoremuneracion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='nomina.empleadocierre')),
            ],
        ),
    ]
