# Generated by Django 5.2.1 on 2025-07-30 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidenciacierre',
            options={'ordering': ['-fecha_detectada', '-impacto_monetario']},
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='comentario_resolucion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='datos_adicionales',
            field=models.JSONField(default=dict, help_text='Datos específicos según tipo de incidencia y comparación'),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='empleado_nombre',
            field=models.CharField(blank=True, help_text='Nombre del empleado (desde consolidación)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='tipo_comparacion',
            field=models.CharField(choices=[('individual', 'Comparación Individual (Elemento a Elemento)'), ('suma_total', 'Comparación Suma Total (Agregada)'), ('regla_negocio', 'Validación Regla de Negocio'), ('legacy', 'Sistema Legacy (Compatibilidad)')], default='legacy', help_text='Tipo de análisis que detectó esta incidencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='rut_empleado',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='tipo_incidencia',
            field=models.CharField(choices=[('variacion_concepto', 'Variación de Concepto (>30%)'), ('concepto_nuevo', 'Concepto Nuevo'), ('concepto_perdido', 'Concepto Perdido'), ('empleado_deberia_ingresar', 'Empleado que Debería Ingresar'), ('empleado_no_deberia_estar', 'Empleado que No Debería Estar'), ('ausentismo_continuo', 'Ausentismo Continuo'), ('variacion_concepto_individual', 'Variación Individual en Concepto'), ('concepto_nuevo_empleado', 'Concepto Nuevo para Empleado'), ('concepto_eliminado_empleado', 'Concepto Eliminado de Empleado'), ('empleado_nuevo', 'Empleado Nuevo sin Período Anterior'), ('variacion_suma_total', 'Variación en Suma Total de Concepto'), ('concepto_nuevo_periodo', 'Concepto Nuevo en Período'), ('concepto_eliminado_periodo', 'Concepto Eliminado del Período'), ('regla_negocio_violada', 'Violación de Regla de Negocio'), ('calculo_incorrecto', 'Error en Cálculo')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='incidenciacierre',
            index=models.Index(fields=['cierre', 'tipo_comparacion'], name='nomina_inci_cierre__015818_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenciacierre',
            index=models.Index(fields=['tipo_comparacion', 'estado'], name='nomina_inci_tipo_co_4cec8f_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenciacierre',
            index=models.Index(fields=['prioridad', 'fecha_detectada'], name='nomina_inci_priorid_aff18e_idx'),
        ),
    ]
