# Generated by Django 5.2.1 on 2025-07-21 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del control a realizar', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('no_realizado', 'No Realizado'), ('omitido', 'Omitido por Supervisor')], default='pendiente', help_text='Estado actual del item', max_length=20)),
                ('comentario', models.TextField(blank=True, help_text='Comentario o observación del analista/supervisor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de ejecución del item')),
                ('categoria', models.CharField(default='general', help_text='Categoría del control (general, validacion, revision, etc.)', max_length=50)),
                ('es_obligatorio', models.BooleanField(default=True, help_text='Si es obligatorio para cerrar la nómina')),
                ('cierre', models.ForeignKey(help_text='Cierre al que pertenece este item del checklist', on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='nomina.cierrenomina')),
                ('usuario_modificacion', models.ForeignKey(blank=True, help_text='Usuario que realizó la última modificación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Items de Checklist',
                'ordering': ['orden', 'fecha_creacion'],
                'indexes': [models.Index(fields=['cierre', 'estado'], name='nomina_chec_cierre__f763e1_idx'), models.Index(fields=['categoria', 'orden'], name='nomina_chec_categor_f7fa50_idx')],
            },
        ),
    ]
