# Generated by Django 5.2.1 on 2025-05-29 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('centro_costo', models.CharField(blank=True, max_length=255)),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_imponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sueldo_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dias_trabajados', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=100)),
                ('sindicato', models.CharField(blank=True, max_length=255)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina', to='nomina.cierrenomina')),
            ],
            options={
                'verbose_name': 'Empleado en Nómina',
                'verbose_name_plural': 'Empleados en Nómina',
            },
        ),
    ]
