# Generated by Django 5.2.1 on 2025-07-31 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_alter_incidenciacierre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_cierre', models.JSONField(help_text='Datos consolidados del cierre de nómina')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('version_calculo', models.CharField(default='1.0', max_length=10)),
                ('tiempo_calculo', models.DurationField(blank=True, null=True)),
                ('cierre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='nomina.cierrenomina')),
            ],
            options={
                'verbose_name': 'Informe de Nómina',
                'verbose_name_plural': 'Informes de Nómina',
                'db_table': 'nomina_informe_cierre',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
