# Generated by Django 5.2.1 on 2025-06-09 17:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_conceptoremuneracion_usuario_clasifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconceptoempleado',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 9, 17, 27, 3, 330145, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroconceptoempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre'),
        ),
        migrations.AlterField(
            model_name='registroconceptoempleado',
            name='monto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registroconceptoempleado',
            name='nombre_concepto_original',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='registroconceptoempleado',
            unique_together={('empleado', 'nombre_concepto_original')},
        ),
    ]
