# Generated by Django 5.2.1 on 2025-05-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_alter_novedad_monto_checklistcierrenomina_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novedad',
            options={'verbose_name': 'Novedad', 'verbose_name_plural': 'Empleados en Nómina'},
        ),
    ]
