# Generated by Django 5.2.1 on 2025-09-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_informenomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroremuneracionesupload',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('analizando_hdrs', 'Analizando Headers'), ('hdrs_analizados', 'Headers Analizados'), ('clasif_en_proceso', 'Clasificación en Proceso'), ('clasif_pendiente', 'Clasificación Pendiente'), ('clasificado', 'Clasificado'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('con_error', 'Con Error')], default='pendiente', max_length=60),
        ),
    ]
