# Generated by Django 5.2.1 on 2025-06-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_registroconceptoempleado_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoAltaBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12)),
                ('empresa_nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(max_length=120)),
                ('centro_de_costo', models.CharField(max_length=120)),
                ('sucursal', models.CharField(max_length=120)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(max_length=80)),
                ('dias_trabajados', models.IntegerField()),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alta_o_baja', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12)),
                ('empresa_nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(max_length=120)),
                ('centro_de_costo', models.CharField(max_length=120)),
                ('sucursal', models.CharField(max_length=120)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_vacaciones', models.DateField()),
                ('fecha_retorno', models.DateField()),
                ('cantidad_dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoVariacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12)),
                ('empresa_nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(max_length=120)),
                ('centro_de_costo', models.CharField(max_length=120)),
                ('sucursal', models.CharField(max_length=120)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_contrato_anterior', models.CharField(max_length=80)),
                ('tipo_contrato_actual', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoVariacionSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12)),
                ('empresa_nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(max_length=120)),
                ('centro_de_costo', models.CharField(max_length=120)),
                ('sucursal', models.CharField(max_length=120)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_contrato', models.CharField(max_length=80)),
                ('sueldo_base_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sueldo_base_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_reajuste', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variacion_pesos', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='movimientofiniquito',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='movimientofiniquito',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='movimientoingreso',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='movimientoingreso',
            name='empleado',
        ),
        migrations.RenameField(
            model_name='movimientoausentismo',
            old_name='nombre',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='movimientoausentismo',
            old_name='fecha_fin',
            new_name='fecha_fin_ausencia',
        ),
        migrations.RenameField(
            model_name='movimientoausentismo',
            old_name='fecha_inicio',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='movimientoausentismo',
            old_name='tipo_ausentismo',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='movimientoausentismo',
            name='centro_de_costo',
            field=models.CharField(default='N/A', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoausentismo',
            name='empresa_nombre',
            field=models.CharField(default='N/A', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoausentismo',
            name='fecha_inicio_ausencia',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoausentismo',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movimientoausentismo',
            name='nombres_apellidos',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoausentismo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimientoausentismo',
            name='sucursal',
            field=models.CharField(default='N/A', max_length=120),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='movimientoausentismo',
            index=models.Index(fields=['cierre', 'rut'], name='nomina_movi_cierre__8dee6d_idx'),
        ),
        migrations.AddField(
            model_name='movimientoaltabaja',
            name='cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina'),
        ),
        migrations.AddField(
            model_name='movimientoaltabaja',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre'),
        ),
        migrations.AddField(
            model_name='movimientovacaciones',
            name='cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina'),
        ),
        migrations.AddField(
            model_name='movimientovacaciones',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre'),
        ),
        migrations.AddField(
            model_name='movimientovariacioncontrato',
            name='cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina'),
        ),
        migrations.AddField(
            model_name='movimientovariacioncontrato',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre'),
        ),
        migrations.AddField(
            model_name='movimientovariacionsueldo',
            name='cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina'),
        ),
        migrations.AddField(
            model_name='movimientovariacionsueldo',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre'),
        ),
        migrations.DeleteModel(
            name='MovimientoFiniquito',
        ),
        migrations.DeleteModel(
            name='MovimientoIngreso',
        ),
        migrations.AddIndex(
            model_name='movimientoaltabaja',
            index=models.Index(fields=['cierre', 'rut'], name='nomina_movi_cierre__f2c8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientovacaciones',
            index=models.Index(fields=['cierre', 'rut'], name='nomina_movi_cierre__cd2f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientovariacioncontrato',
            index=models.Index(fields=['cierre', 'rut'], name='nomina_movi_cierre__361fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientovariacionsueldo',
            index=models.Index(fields=['cierre', 'rut'], name='nomina_movi_cierre__672dd4_idx'),
        ),
    ]
