# Generated by Django 5.2.1 on 2025-06-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_movimientoaltabaja_movimientovacaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosmesupload',
            name='resultados_procesamiento',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='movimientosmesupload',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('procesado', 'Procesado'), ('con_error', 'Con Error'), ('con_errores_parciales', 'Con Errores Parciales')], default='pendiente', max_length=30),
        ),
    ]
