# Generated by Django 5.2.1 on 2025-08-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_eliminar_estado_cargando_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrenomina',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('archivos_completos', 'Archivos Completos'), ('verificacion_datos', 'Verificación de Datos'), ('verificado_sin_discrepancias', 'Verificado Sin Discrepancias'), ('datos_consolidados', 'Datos Consolidados'), ('con_discrepancias', 'Con Discrepancias'), ('con_incidencias', 'Con Incidencias'), ('incidencias_resueltas', 'Incidencias Resueltas'), ('requiere_recarga_archivos', 'Requiere Recarga de Archivos'), ('validacion_final', 'Validación Final'), ('generando_informe', 'Generando Informe'), ('finalizado', 'Finalizado')], default='pendiente', max_length=40),
        ),
    ]
