# Generated by Django 5.2.1 on 2025-05-30 23:27

import django.db.models.deletion
import nomina.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('nomina', '0004_alter_novedad_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistcierrenomina',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='checklistcierrenomina',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='comentarioincidencia',
            name='incidencia',
        ),
        migrations.RemoveField(
            model_name='comentarioincidencia',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='conceptoclasificado',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conceptoclasificado',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='novedad',
            name='concepto',
            field=models.CharField(max_length=120),
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='incidencianomina',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='incidencianomina',
            name='creada_por',
        ),
        migrations.RemoveField(
            model_name='incidencianomina',
            name='respondida_por',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='nominaempleado',
            name='cierre',
        ),
        migrations.AlterModelOptions(
            name='novedad',
            options={},
        ),
        migrations.RemoveField(
            model_name='cierrenomina',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='comentario',
        ),
        migrations.AddField(
            model_name='cierrenomina',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrenomina',
            name='usuario_analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_analista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cierrenomina',
            name='usuario_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novedad',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('haber', 'Haber'), ('descuento', 'Descuento'), ('informacion', 'Información')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='hashtags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cierrenomina',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('listo_para_revision', 'Listo para Revisión'), ('aprobado', 'Aprobado'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='ArchivoAnalistaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('ingresos', 'Ingresos'), ('finiquitos', 'Finiquitos'), ('ausentismos', 'Ausentismos')], max_length=20)),
                ('archivo', models.FileField(upload_to=nomina.models.analista_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('procesado', 'Procesado'), ('con_error', 'Con Error')], default='pendiente', max_length=20)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_analista', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoNovedadesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=nomina.models.novedades_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('procesado', 'Procesado'), ('con_error', 'Con Error')], default='pendiente', max_length=20)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_novedades', to='nomina.cierrenomina')),
            ],
        ),
        migrations.AddField(
            model_name='novedad',
            name='archivo_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='nomina.archivonovedadesupload'),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('no_realizado', 'No Realizado')], default='pendiente', max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoRemuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concepto', models.CharField(max_length=120)),
                ('clasificacion', models.CharField(choices=[('haber', 'Haber'), ('descuento', 'Descuento'), ('informacion', 'Información')], max_length=20)),
                ('hashtags', models.JSONField(default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario_clasifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cliente', 'nombre_concepto')},
            },
        ),
        migrations.AddField(
            model_name='novedad',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.conceptoremuneracion'),
        ),
        migrations.CreateModel(
            name='IncidenciaComparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12)),
                ('detalle', models.TextField()),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_comparacion', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('concepto', models.CharField(max_length=120)),
                ('monto_novedad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_libro', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tipo_incidencia', models.CharField(max_length=60)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_resuelto', models.DateTimeField(blank=True, null=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_novedad', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='LibroRemuneracionesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=nomina.models.libro_remuneraciones_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('procesado', 'Procesado'), ('con_error', 'Con Error')], default='pendiente', max_length=20)),
                ('header_json', models.JSONField(default=list)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_remuneraciones', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientosMesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=nomina.models.movimientos_mes_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('procesado', 'Procesado'), ('con_error', 'Con Error')], default='pendiente', max_length=20)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_mes', to='nomina.cierrenomina')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoAusentismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_ausentismo', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.IntegerField()),
                ('movimientos_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.movimientosmesupload')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoAltaBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_movimiento', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], max_length=20)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=120, null=True)),
                ('movimientos_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.movimientosmesupload')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.IntegerField()),
                ('movimientos_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.movimientosmesupload')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAusentismoAnalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_ausentismo', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.IntegerField()),
                ('archivo_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.archivoanalistaupload')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFiniquitoAnalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_finiquito', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=120, null=True)),
                ('archivo_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.archivoanalistaupload')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIngresoAnalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_ingreso', models.DateField()),
                ('cargo', models.CharField(blank=True, max_length=80, null=True)),
                ('archivo_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.archivoanalistaupload')),
            ],
        ),
        migrations.CreateModel(
            name='VariacionSueldoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('sueldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sueldo_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('movimientos_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.movimientosmesupload')),
            ],
        ),
        migrations.CreateModel(
            name='VariacionTipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_anterior', models.CharField(max_length=80)),
                ('tipo_nuevo', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
                ('movimientos_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.movimientosmesupload')),
            ],
        ),
        migrations.DeleteModel(
            name='Ausentismo',
        ),
        migrations.DeleteModel(
            name='ChecklistCierreNomina',
        ),
        migrations.DeleteModel(
            name='ComentarioIncidencia',
        ),
        migrations.DeleteModel(
            name='ConceptoClasificado',
        ),
        migrations.DeleteModel(
            name='Finiquito',
        ),
        migrations.DeleteModel(
            name='IncidenciaNomina',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
        migrations.DeleteModel(
            name='NominaEmpleado',
        ),
    ]
