# Generated by Django 5.2.1 on 2025-09-03 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_alter_libroremuneracionesupload_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVerificacionCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_intento', models.PositiveIntegerField(help_text='Número de intento de verificación (1, 2, 3...)')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('tiempo_ejecucion', models.PositiveIntegerField(blank=True, help_text='Duración en segundos', null=True)),
                ('total_discrepancias_encontradas', models.PositiveIntegerField(default=0)),
                ('discrepancias_libro_vs_novedades', models.PositiveIntegerField(default=0)),
                ('discrepancias_movimientos_vs_analista', models.PositiveIntegerField(default=0)),
                ('estado_verificacion', models.CharField(choices=[('iniciado', 'Verificación Iniciada'), ('procesando', 'Procesando Verificación'), ('completado', 'Verificación Completada'), ('error', 'Error en Verificación'), ('cancelado', 'Verificación Cancelada')], default='iniciado', max_length=20)),
                ('task_id', models.CharField(blank=True, help_text='ID de la tarea Celery', max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Notas del analista sobre esta verificación', null=True)),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si falló', null=True)),
                ('archivos_analizados', models.JSONField(default=dict, help_text='Información sobre archivos analizados en esta verificación')),
                ('estadisticas_procesamiento', models.JSONField(default=dict, help_text='Estadísticas detalladas del procesamiento')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_verificaciones', to='nomina.cierrenomina')),
                ('usuario_ejecutor', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la verificación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Verificación',
                'verbose_name_plural': 'Historiales de Verificación',
                'ordering': ['-numero_intento', '-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='DiscrepanciaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_discrepancia', models.CharField(max_length=50)),
                ('rut_empleado', models.CharField(db_index=True, max_length=20)),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('concepto', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_esperado', models.CharField(blank=True, max_length=500, null=True)),
                ('valor_encontrado', models.CharField(blank=True, max_length=500, null=True)),
                ('diferencia', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion_detallada', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_deteccion', models.PositiveIntegerField(help_text='Orden en que se detectó esta discrepancia')),
                ('solucionada_en_siguiente', models.BooleanField(default=False, help_text='¿Esta discrepancia fue solucionada en la siguiente verificación?')),
                ('historial_verificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancias_detectadas', to='nomina.historialverificacioncierre')),
            ],
            options={
                'verbose_name': 'Discrepancia en Historial',
                'verbose_name_plural': 'Discrepancias en Historial',
                'ordering': ['-fecha_creacion', 'orden_deteccion'],
            },
        ),
        migrations.AddField(
            model_name='discrepanciacierre',
            name='historial_verificacion',
            field=models.ForeignKey(blank=True, help_text='Verificación en la que se detectó esta discrepancia', null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.historialverificacioncierre'),
        ),
        migrations.AddIndex(
            model_name='historialverificacioncierre',
            index=models.Index(fields=['cierre', 'numero_intento'], name='nomina_hist_cierre__b7c387_idx'),
        ),
        migrations.AddIndex(
            model_name='historialverificacioncierre',
            index=models.Index(fields=['fecha_ejecucion'], name='nomina_hist_fecha_e_66ab1c_idx'),
        ),
        migrations.AddIndex(
            model_name='historialverificacioncierre',
            index=models.Index(fields=['estado_verificacion'], name='nomina_hist_estado__ac01d1_idx'),
        ),
        migrations.AddIndex(
            model_name='historialverificacioncierre',
            index=models.Index(fields=['total_discrepancias_encontradas'], name='nomina_hist_total_d_3c09f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historialverificacioncierre',
            unique_together={('cierre', 'numero_intento')},
        ),
        migrations.AddIndex(
            model_name='discrepanciahistorial',
            index=models.Index(fields=['historial_verificacion', 'orden_deteccion'], name='nomina_disc_histori_1f1854_idx'),
        ),
        migrations.AddIndex(
            model_name='discrepanciahistorial',
            index=models.Index(fields=['rut_empleado'], name='nomina_disc_rut_emp_1c5701_idx'),
        ),
        migrations.AddIndex(
            model_name='discrepanciahistorial',
            index=models.Index(fields=['fecha_creacion'], name='nomina_disc_fecha_c_c430dd_idx'),
        ),
    ]
