# Generated by Django 5.2.1 on 2025-06-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_movimientosmesupload_resultados_procesamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalistaFiniquito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_retiro', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('archivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.archivoanalistaupload')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre')),
            ],
            options={
                'indexes': [models.Index(fields=['cierre', 'rut'], name='nomina_anal_cierre__c460cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalistaIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio_ausencia', models.DateField()),
                ('fecha_fin_ausencia', models.DateField()),
                ('dias', models.IntegerField()),
                ('tipo_ausentismo', models.CharField(max_length=80)),
                ('archivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.archivoanalistaupload')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre')),
            ],
            options={
                'indexes': [models.Index(fields=['cierre', 'rut'], name='nomina_anal_cierre__a1040c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalistaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_ingreso', models.DateField()),
                ('archivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.archivoanalistaupload')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre')),
            ],
            options={
                'indexes': [models.Index(fields=['cierre', 'rut'], name='nomina_anal_cierre__6ec0a8_idx')],
            },
        ),
    ]
