# Generated by Django 5.2.1 on 2025-05-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_remove_checklistcierrenomina_cierre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrenomina',
            name='periodo',
            field=models.DateField(),
        ),
    ]
