# Generated by Django 5.2.1 on 2025-08-05 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_alter_cierrenomina_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteNomina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('costos_personal', 'Reporte de Costos de Personal'), ('rotacion_personal', 'Análisis de Rotación de Personal'), ('indicadores_rrhh', 'Indicadores de Recursos Humanos'), ('ausentismo', 'Reporte de Ausentismo'), ('remuneraciones', 'Análisis de Remuneraciones'), ('productividad', 'Reporte de Productividad'), ('dotacion', 'Análisis de Dotación'), ('comparativo_periodos', 'Comparativo entre Períodos')], max_length=30)),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='generando', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('datos_reporte', models.JSONField(blank=True, help_text='Datos estructurados del reporte de nómina', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre el reporte (tiempo generación, versión, KPIs, etc.)')),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si la generación falló')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='nomina.cierrenomina')),
                ('usuario_generador', models.ForeignKey(help_text='Usuario que solicitó la generación del reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Nómina',
                'verbose_name_plural': 'Reportes de Nómina',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.DeleteModel(
            name='InformeNomina',
        ),
        migrations.AddIndex(
            model_name='reportenomina',
            index=models.Index(fields=['cierre', 'tipo_reporte'], name='nomina_repo_cierre__246488_idx'),
        ),
        migrations.AddIndex(
            model_name='reportenomina',
            index=models.Index(fields=['estado', 'fecha_generacion'], name='nomina_repo_estado_e1398c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportenomina',
            index=models.Index(fields=['tipo_reporte', 'estado'], name='nomina_repo_tipo_re_1de212_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportenomina',
            unique_together={('cierre', 'tipo_reporte')},
        ),
    ]
