# Generated by Django 5.2.1 on 2025-05-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_alter_cierrenomina_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrenomina',
            name='periodo',
            field=models.CharField(max_length=7),
        ),
    ]
