# Generated by Django 5.2.1 on 2025-08-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_reportenomina_delete_informenomina_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='headervalorempleado',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='headervalorempleado',
            name='concepto_remuneracion',
        ),
        migrations.RemoveField(
            model_name='headervalorempleado',
            name='nomina_consolidada',
        ),
        migrations.RemoveIndex(
            model_name='nominaconsolidada',
            name='nomina_nomi_cierre__8f9772_idx',
        ),
        migrations.RemoveField(
            model_name='conceptoconsolidado',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='conceptoconsolidado',
            name='fecha_consolidacion',
        ),
        migrations.RemoveField(
            model_name='nominaconsolidada',
            name='estado_empleado',
        ),
        migrations.RemoveField(
            model_name='nominaconsolidada',
            name='fecha_consolidacion',
        ),
        migrations.RemoveField(
            model_name='nominaconsolidada',
            name='fuente_datos',
        ),
        migrations.AddIndex(
            model_name='nominaconsolidada',
            index=models.Index(fields=['cierre'], name='nomina_nomi_cierre__aa3ab5_idx'),
        ),
        migrations.DeleteModel(
            name='HeaderValorEmpleado',
        ),
    ]
