# Generated by Django 5.2.1 on 2025-06-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_analistafiniquito_analistaincidencia_analistaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoanalistaupload',
            name='tipo_archivo',
            field=models.CharField(choices=[('ingresos', 'Ingresos'), ('finiquitos', 'Finiquitos'), ('incidencias', 'Incidencias')], max_length=20),
        ),
    ]
