# Generated by Django 5.2.1 on 2025-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_alter_cierrenomina_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroremuneracionesupload',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('clasif_pendiente', 'Clasificación Pendiente'), ('clasificado', 'Clasificado'), ('con_error', 'Con Error')], default='pendiente', max_length=30),
        ),
    ]
