# Generated by Django 5.2.1 on 2025-06-11 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('nomina', '0007_alter_archivoanalistaupload_tipo_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivonovedadesupload',
            name='header_json',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='archivonovedadesupload',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('analizando_hdrs', 'Analizando Headers'), ('hdrs_analizados', 'Headers Analizados'), ('clasif_en_proceso', 'Clasificación en Proceso'), ('clasif_pendiente', 'Clasificación Pendiente'), ('clasificado', 'Clasificado'), ('procesado', 'Procesado'), ('con_error', 'Con Error')], default='pendiente', max_length=60),
        ),
        migrations.CreateModel(
            name='ConceptoRemuneracionNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concepto', models.CharField(max_length=120)),
                ('clasificacion', models.CharField(choices=[('haber', 'Haber'), ('descuento', 'Descuento'), ('informacion', 'Información')], max_length=20)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('vigente', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario_clasifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos_novedades_clasificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cliente', 'nombre_concepto')},
            },
        ),
        migrations.CreateModel(
            name='EmpleadoCierreNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido_paterno', models.CharField(max_length=120)),
                ('apellido_materno', models.CharField(blank=True, max_length=120)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_novedades', to='nomina.cierrenomina')),
            ],
            options={
                'unique_together': {('cierre', 'rut')},
            },
        ),
        migrations.CreateModel(
            name='RegistroConceptoEmpleadoNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concepto_original', models.CharField(max_length=200)),
                ('monto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.conceptoremuneracionnovedades')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierrenovedades')),
            ],
            options={
                'unique_together': {('empleado', 'nombre_concepto_original')},
            },
        ),
    ]
