# Generated by Django 5.2.1 on 2025-06-11 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('nomina', '0008_archivonovedadesupload_header_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptoremuneracionnovedades',
            old_name='vigente',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='conceptoremuneracionnovedades',
            old_name='nombre_concepto',
            new_name='nombre_concepto_novedades',
        ),
        migrations.AlterUniqueTogether(
            name='conceptoremuneracionnovedades',
            unique_together={('cliente', 'nombre_concepto_novedades')},
        ),
        migrations.AddField(
            model_name='conceptoremuneracionnovedades',
            name='concepto_libro',
            field=models.ForeignKey(blank=True, help_text='Concepto del libro de remuneraciones al que mapea este header de novedades', null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.conceptoremuneracion'),
        ),
        migrations.AddField(
            model_name='conceptoremuneracionnovedades',
            name='fecha_mapeo',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptoremuneracionnovedades',
            name='usuario_mapea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapeos_novedades_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='conceptoremuneracionnovedades',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='conceptoremuneracionnovedades',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='conceptoremuneracionnovedades',
            name='usuario_clasifica',
        ),
    ]
