# Generated by Django 5.2.1 on 2025-06-27 23:48

import django.db.models.deletion
import nomina.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_supervisor_relation'),
        ('nomina', '0010_cierrenomina_estado_incidencias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLogNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_upload', models.CharField(choices=[('libro_remuneraciones', 'Libro de Remuneraciones'), ('movimientos_mes', 'Movimientos del Mes'), ('novedades', 'Novedades'), ('movimientos_ingresos', 'Movimientos - Ingresos'), ('movimientos_egresos', 'Movimientos - Egresos'), ('movimientos_vacaciones', 'Movimientos - Vacaciones'), ('movimientos_variacion_sueldo', 'Movimientos - Variación Sueldo'), ('movimientos_variacion_contrato', 'Movimientos - Variación Contrato'), ('movimientos_finiquitos', 'Movimientos - Finiquitos'), ('movimientos_incidencias', 'Movimientos - Incidencias')], max_length=35)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(blank=True, help_text='Ruta relativa del archivo en storage', max_length=500)),
                ('tamaño_archivo', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('hash_archivo', models.CharField(blank=True, help_text='SHA-256 del archivo para detección de duplicados', max_length=64)),
                ('estado', models.CharField(choices=[('subido', 'Archivo subido'), ('procesando', 'Procesando'), ('analizando_hdrs', 'Analizando Headers'), ('hdrs_analizados', 'Headers Analizados'), ('clasif_en_proceso', 'Clasificación en Proceso'), ('clasif_pendiente', 'Clasificación Pendiente'), ('clasificado', 'Clasificado'), ('completado', 'Procesado correctamente'), ('procesado', 'Procesado'), ('error', 'Con errores'), ('con_errores_parciales', 'Con Errores Parciales'), ('datos_eliminados', 'Datos procesados eliminados')], default='subido', max_length=25)),
                ('errores', models.TextField(blank=True)),
                ('resumen', models.JSONField(blank=True, help_text='Resumen detallado del procesamiento', null=True)),
                ('registros_procesados', models.PositiveIntegerField(default=0, help_text='Total de registros procesados')),
                ('registros_exitosos', models.PositiveIntegerField(default=0, help_text='Registros procesados exitosamente')),
                ('registros_fallidos', models.PositiveIntegerField(default=0, help_text='Registros que fallaron en el procesamiento')),
                ('headers_detectados', models.JSONField(default=list, help_text='Headers detectados en el archivo')),
                ('tiempo_procesamiento', models.DurationField(blank=True, null=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('cierre', models.ForeignKey(blank=True, help_text='Cierre de nómina asociado al upload', null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Upload Nómina',
                'verbose_name_plural': 'Logs de Uploads Nómina',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaActivityLogNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta', models.CharField(choices=[('libro_remuneraciones', 'Tarjeta 1: Libro de Remuneraciones'), ('movimientos_mes', 'Tarjeta 2: Movimientos del Mes'), ('analista_ingresos', 'Tarjeta 3a: Movimientos - Ingresos'), ('analista_egresos', 'Tarjeta 3b: Movimientos - Egresos'), ('analista_vacaciones', 'Tarjeta 3c: Movimientos - Vacaciones'), ('analista_variacion_sueldo', 'Tarjeta 3d: Movimientos - Variación Sueldo'), ('analista_variacion_contrato', 'Tarjeta 3e: Movimientos - Variación Contrato'), ('analista_finiquitos', 'Tarjeta 3f: Movimientos - Finiquitos'), ('analista_incidencias', 'Tarjeta 3g: Movimientos - Incidencias'), ('novedades', 'Tarjeta 4: Novedades'), ('incidencias', 'Tarjeta 5: Incidencias'), ('revision', 'Tarjeta 6: Revisión'), ('modal_mapeo_novedades', 'Modal: Mapeo Novedades'), ('modal_clasificacion', 'Modal: Clasificación Conceptos')], max_length=30)),
                ('accion', models.CharField(choices=[('upload_excel', 'Subida de Excel'), ('reprocesar_archivo', 'Reprocesar Archivo'), ('analizar_headers', 'Análisis de Headers'), ('mapear_headers', 'Mapeo de Headers'), ('clasificar_conceptos', 'Clasificación de Conceptos'), ('procesar_final', 'Procesamiento Final'), ('manual_create', 'Creación Manual'), ('manual_edit', 'Edición Manual'), ('manual_delete', 'Eliminación Manual'), ('bulk_delete', 'Eliminación Masiva'), ('view_data', 'Visualización de Datos'), ('view_modal', 'Apertura de Modal'), ('modal_action', 'Acción en Modal'), ('export_data', 'Exportación de Datos'), ('validation_error', 'Error de Validación'), ('process_start', 'Inicio de Procesamiento'), ('process_complete', 'Procesamiento Completado'), ('incidencia_create', 'Creación de Incidencia'), ('incidencia_resolve', 'Resolución de Incidencia'), ('revision_submit', 'Envío a Revisión'), ('revision_approve', 'Aprobación de Revisión'), ('revision_reject', 'Rechazo de Revisión')], max_length=25)),
                ('descripcion', models.TextField()),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('exito', 'Exitoso'), ('error', 'Error'), ('warning', 'Advertencia')], default='exito', max_length=10)),
                ('empleado_rut', models.CharField(blank=True, help_text='RUT del empleado afectado', max_length=12)),
                ('concepto_afectado', models.CharField(blank=True, help_text='Concepto de remuneración afectado', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs_nomina', to='nomina.cierrenomina')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('archivo_relacionado', models.ForeignKey(blank=True, help_text='Referencia al upload log relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.uploadlognomina')),
            ],
            options={
                'verbose_name': 'Log de Actividad de Tarjeta Nómina',
                'verbose_name_plural': 'Logs de Actividad de Tarjetas Nómina',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MovimientosAnalistaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('ingresos', 'Ingresos'), ('egresos', 'Egresos'), ('vacaciones', 'Vacaciones'), ('variacion_sueldo', 'Variación Sueldo'), ('variacion_contrato', 'Variación Contrato'), ('finiquitos', 'Finiquitos'), ('incidencias', 'Incidencias')], max_length=25)),
                ('archivo', models.FileField(upload_to=nomina.models.analista_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('errores', models.TextField(blank=True)),
                ('resumen_procesamiento', models.JSONField(default=dict)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina')),
                ('upload_log', models.ForeignKey(blank=True, help_text='Referencia al log del upload que generó este archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.uploadlognomina')),
            ],
        ),
        migrations.AddIndex(
            model_name='uploadlognomina',
            index=models.Index(fields=['cliente', 'tipo_upload'], name='nomina_uplo_cliente_80a255_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadlognomina',
            index=models.Index(fields=['estado', 'fecha_subida'], name='nomina_uplo_estado_35590f_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadlognomina',
            index=models.Index(fields=['tipo_upload', 'estado'], name='nomina_uplo_tipo_up_ac3588_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadlognomina',
            index=models.Index(fields=['cierre', 'tipo_upload'], name='nomina_uplo_cierre__63d030_idx'),
        ),
        migrations.AddIndex(
            model_name='tarjetaactivitylognomina',
            index=models.Index(fields=['cierre', 'tarjeta'], name='nomina_tarj_cierre__dcbaec_idx'),
        ),
        migrations.AddIndex(
            model_name='tarjetaactivitylognomina',
            index=models.Index(fields=['usuario', 'timestamp'], name='nomina_tarj_usuario_36363d_idx'),
        ),
        migrations.AddIndex(
            model_name='tarjetaactivitylognomina',
            index=models.Index(fields=['tarjeta', 'accion'], name='nomina_tarj_tarjeta_befaec_idx'),
        ),
        migrations.AddIndex(
            model_name='tarjetaactivitylognomina',
            index=models.Index(fields=['empleado_rut', 'cierre'], name='nomina_tarj_emplead_4dd201_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosanalistaupload',
            index=models.Index(fields=['cierre', 'tipo_archivo'], name='nomina_movi_cierre__d86ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosanalistaupload',
            index=models.Index(fields=['procesado', 'fecha_subida'], name='nomina_movi_procesa_477316_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='movimientosanalistaupload',
            unique_together={('cierre', 'tipo_archivo')},
        ),
    ]
