# Generated by Django 5.2.1 on 2025-07-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0011_uploadlognomina_tarjetaactivitylognomina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptoremuneracion',
            name='clasificacion',
            field=models.CharField(choices=[('haberes_imponibles', 'Haberes Imponibles'), ('haberes_no_imponibles', 'Haberes No Imponibles'), ('horas_extras', 'Horas Extras'), ('descuentos_legales', 'Descuentos Legales'), ('otros_descuentos', 'Otros Descuentos'), ('aportes_patronales', 'Aportes Patronales'), ('informacion_adicional', 'Información Adicional (No Monto)'), ('impuestos', 'Impuestos')], max_length=30),
        ),
    ]
