# Generated by Django 5.2.1 on 2025-06-04 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0011_empleado_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "cierre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_nomina",
                        to="nomina.cierrenomina",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_nomina",
                        to="nomina.empleado",
                    ),
                ),
            ],
            options={
                "unique_together": {("cierre", "empleado")},
            },
        ),
    ]
