# Generated by Django 5.2.1 on 2025-06-05 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('nomina', '0012_registronomina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registronomina',
            name='data',
        ),
        migrations.CreateModel(
            name='EmpleadosMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('rut_empresa', models.CharField(max_length=20)),
                ('rut_trabajador', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido_paterno', models.CharField(max_length=120)),
                ('apellido_materno', models.CharField(blank=True, max_length=120)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_mes', to='nomina.cierrenomina')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='incidenciacomparacion',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='incidencianovedad',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='movimientoaltabaja',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='movimientoausentismo',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='movimientovacaciones',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='registroausentismoanalista',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='registrofiniquitoanalista',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='registroingresoanalista',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='registronomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_nomina', to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='variacionsueldobase',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.AlterField(
            model_name='variaciontipocontrato',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadosmes'),
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
