# Generated by Django 5.2.1 on 2025-07-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0012_alter_conceptoremuneracion_clasificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoausentismo',
            name='fecha_ingreso',
        ),
    ]
