# Generated by Django 5.2.1 on 2025-07-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0013_remove_movimientoausentismo_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientovacaciones',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientovariacioncontrato',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientovariacionsueldo',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
