# Generated by Django 5.2.1 on 2025-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0013_remove_registronomina_data_empleadosmes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registronomina",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
