# Generated by Django 5.2.1 on 2025-07-09 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0014_alter_movimientovacaciones_fecha_ingreso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisDatosCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_empleados_actual', models.IntegerField(default=0)),
                ('cantidad_ingresos_actual', models.IntegerField(default=0)),
                ('cantidad_finiquitos_actual', models.IntegerField(default=0)),
                ('cantidad_ausentismos_actual', models.IntegerField(default=0)),
                ('cantidad_empleados_anterior', models.IntegerField(default=0)),
                ('cantidad_ingresos_anterior', models.IntegerField(default=0)),
                ('cantidad_finiquitos_anterior', models.IntegerField(default=0)),
                ('cantidad_ausentismos_anterior', models.IntegerField(default=0)),
                ('ausentismos_por_tipo_actual', models.JSONField(default=dict)),
                ('ausentismos_por_tipo_anterior', models.JSONField(default=dict)),
                ('tolerancia_variacion_salarial', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cierre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_datos', to='nomina.cierrenomina')),
            ],
            options={
                'verbose_name': 'Análisis de Datos del Cierre',
                'verbose_name_plural': 'Análisis de Datos de Cierres',
                'ordering': ['-fecha_analisis'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaVariacionSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empleado', models.CharField(max_length=12)),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('sueldo_base_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sueldo_base_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje_variacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_variacion', models.CharField(choices=[('aumento', 'Aumento'), ('disminucion', 'Disminución')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_analisis', 'En Análisis'), ('justificado', 'Justificado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('justificacion_analista', models.TextField(blank=True)),
                ('fecha_justificacion', models.DateTimeField(blank=True, null=True)),
                ('comentario_supervisor', models.TextField(blank=True)),
                ('fecha_resolucion_supervisor', models.DateTimeField(blank=True, null=True)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_accion', models.DateTimeField(auto_now=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_variacion', to='nomina.analisisdatoscierre')),
                ('analista_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_variacion_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina')),
                ('supervisor_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_variacion_supervisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia de Variación Salarial',
                'verbose_name_plural': 'Incidencias de Variación Salarial',
                'ordering': ['-fecha_deteccion'],
                'indexes': [models.Index(fields=['cierre', 'estado'], name='nomina_inci_cierre__fc7c6b_idx'), models.Index(fields=['analista_asignado', 'estado'], name='nomina_inci_analist_11c3e9_idx'), models.Index(fields=['supervisor_revisor', 'estado'], name='nomina_inci_supervi_035d17_idx'), models.Index(fields=['rut_empleado', 'cierre'], name='nomina_inci_rut_emp_898cbf_idx')],
            },
        ),
    ]
