# Generated by Django 5.2.1 on 2025-06-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0014_registronomina_data"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="empleadosmes",
            unique_together={("cierre", "rut_trabajador")},
        ),
    ]
