# Generated by Django 5.2.1 on 2025-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0015_analisisdatoscierre_incidenciavariacionsalarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrenomina',
            name='estado_incidencias',
            field=models.CharField(choices=[('analisis_pendiente', 'Análisis de Incidencias Pendiente'), ('incidencias_generadas', 'Incidencias Detectadas'), ('archivos_consolidados', 'Archivos Consolidados'), ('analisis_generado', 'Análisis Generado'), ('incidencias_abiertas', 'Incidencias Abiertas'), ('sin_incidencias', 'Sin Incidencias'), ('cerrado', 'Cerrado')], default='analisis_pendiente', max_length=50),
        ),
    ]
