# Generated by Django 5.2.1 on 2025-07-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0021_update_estado_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscrepanciaCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_discrepancia', models.CharField(choices=[('empleado_solo_libro', 'Empleado solo en Libro'), ('empleado_solo_novedades', 'Empleado solo en Novedades'), ('diff_datos_personales', 'Diferencia en Datos Personales'), ('diff_sueldo_base', 'Diferencia en Sueldo Base'), ('diff_concepto_monto', 'Diferencia en Monto por Concepto'), ('concepto_solo_libro', 'Concepto solo en Libro'), ('concepto_solo_novedades', 'Concepto solo en Novedades'), ('ingreso_no_reportado', 'Ingreso no reportado por Analista'), ('finiquito_no_reportado', 'Finiquito no reportado por Analista'), ('ausencia_no_reportada', 'Ausencia no reportada por Analista'), ('diff_fechas_ausencia', 'Diferencia en Fechas de Ausencia'), ('diff_dias_ausencia', 'Diferencia en Días de Ausencia'), ('diff_tipo_ausencia', 'Diferencia en Tipo de Ausencia')], max_length=50)),
                ('rut_empleado', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('valor_libro', models.CharField(blank=True, max_length=500, null=True)),
                ('valor_novedades', models.CharField(blank=True, max_length=500, null=True)),
                ('valor_movimientos', models.CharField(blank=True, max_length=500, null=True)),
                ('valor_analista', models.CharField(blank=True, max_length=500, null=True)),
                ('concepto_afectado', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_detectada', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancias', to='nomina.cierrenomina')),
                ('empleado_libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierre')),
                ('empleado_novedades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.empleadocierrenovedades')),
            ],
            options={
                'verbose_name': 'Discrepancia de Verificación',
                'verbose_name_plural': 'Discrepancias de Verificación',
                'ordering': ['-fecha_detectada'],
                'indexes': [models.Index(fields=['cierre', 'tipo_discrepancia'], name='nomina_disc_cierre__f82337_idx'), models.Index(fields=['rut_empleado', 'cierre'], name='nomina_disc_rut_emp_1e2dc4_idx'), models.Index(fields=['fecha_detectada'], name='nomina_disc_fecha_d_9f5f91_idx')],
            },
        ),
    ]
