# Generated by Django 5.2.1 on 2025-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0022_discrepanciacierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrenomina',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('datos_consolidados', 'Datos Consolidados'), ('discrepancias_detectadas', 'Discrepancias Detectadas'), ('datos_verificados', 'Datos Verificados'), ('reportes_generados', 'Reportes Generados'), ('validacion_senior', 'Validación Senior'), ('completado', 'Completado'), ('analisis_generado', 'Análisis Generado'), ('incidencias_abiertas', 'Incidencias Abiertas'), ('sin_incidencias', 'Sin Incidencias')], default='pendiente', max_length=30),
        ),
    ]
