# Generated by Django 5.2.1 on 2025-07-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0023_alter_cierrenomina_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrenomina',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cargando_archivos', 'Cargando Archivos'), ('archivos_completos', 'Archivos Completos'), ('verificacion_datos', 'Verificación de Datos'), ('verificado_sin_discrepancias', 'Verificado Sin Discrepancias'), ('incidencias_generadas', 'Incidencias Generadas'), ('incidencias_resueltas', 'Incidencias Resueltas'), ('validacion_final', 'Validación Final'), ('completado', 'Completado')], default='pendiente', max_length=40),
        ),
        migrations.AlterField(
            model_name='cierrenomina',
            name='estado_incidencias',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('detectadas', 'Detectadas'), ('en_revision', 'En Revisión'), ('resueltas', 'Resueltas')], default='pendiente', max_length=30),
        ),
    ]
