# Generated by Django 5.2.1 on 2025-07-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0024_alter_cierrenomina_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetaactivitylognomina',
            name='accion',
            field=models.CharField(choices=[('upload_excel', 'Subida de Excel'), ('manual_create', 'Creación Manual'), ('manual_edit', 'Edición Manual'), ('manual_delete', 'Eliminación Manual'), ('bulk_delete', 'Eliminación Masiva'), ('view_data', 'Visualización de Datos'), ('view_list', 'Visualización de Lista'), ('validation_error', 'Error de Validación'), ('process_start', 'Inicio de Procesamiento'), ('process_complete', 'Procesamiento Completado'), ('header_analysis', 'Análisis de Headers'), ('classification_start', 'Inicio de Clasificación'), ('classification_complete', 'Clasificación Completada'), ('reprocesar', 'Reprocesamiento'), ('delete_all', 'Eliminación Total'), ('delete_archivo', 'Eliminación de Archivo'), ('modal_open', 'Apertura de Modal'), ('modal_close', 'Cierre de Modal'), ('view_classification', 'Ver Clasificación'), ('save_classification', 'Guardar Clasificación'), ('download_template', 'Descarga de Plantilla'), ('file_select', 'Selección de Archivo'), ('file_validate', 'Validación de Archivo'), ('state_change', 'Cambio de Estado'), ('polling_start', 'Inicio de Polling'), ('polling_stop', 'Detención de Polling'), ('concept_map', 'Mapeo de Concepto'), ('concept_unmap', 'Desmapeo de Concepto'), ('auto_classify', 'Clasificación Automática'), ('manual_classify', 'Clasificación Manual'), ('headers_detected', 'Headers Detectados'), ('progress_update', 'Actualización de Progreso'), ('error_recovery', 'Recuperación de Error'), ('session_start', 'Inicio de Sesión de Trabajo'), ('session_end', 'Fin de Sesión de Trabajo')], max_length=25),
        ),
    ]
