# Generated by Django 5.2.1 on 2025-07-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0026_alter_cierrenomina_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrenomina',
            name='estado_consolidacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Consolidar'), ('consolidando', 'Consolidando Información'), ('consolidado', 'Información Consolidada'), ('error_consolidacion', 'Error en Consolidación')], default='pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='cierrenomina',
            name='fecha_consolidacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrenomina',
            name='puede_consolidar',
            field=models.BooleanField(default=False, help_text='¿Tiene 0 discrepancias y puede consolidarse?'),
        ),
    ]
