# Generated by Django 5.2.1 on 2025-07-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0027_cierrenomina_estado_consolidacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciacierre',
            name='tipo_incidencia',
            field=models.CharField(choices=[('variacion_concepto', 'Variación de Concepto (>30%)'), ('concepto_nuevo', 'Concepto Nuevo'), ('concepto_perdido', 'Concepto Perdido'), ('empleado_deberia_ingresar', 'Empleado que Debería Ingresar'), ('empleado_no_deberia_estar', 'Empleado que No Debería Estar'), ('ausentismo_continuo', 'Ausentismo Continuo')], max_length=50),
        ),
    ]
