# Generated by Django 5.2.1 on 2025-07-20 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0028_alter_incidenciacierre_tipo_incidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaConsolidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empleado', models.CharField(db_index=True, max_length=20)),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('centro_costo', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_empleado', models.CharField(choices=[('activo', 'Empleado Activo'), ('nueva_incorporacion', 'Nueva Incorporación'), ('finiquito', 'Finiquito'), ('ausente_total', 'Ausente Periodo Completo'), ('ausente_parcial', 'Ausente Parcial')], default='activo', max_length=20)),
                ('total_haberes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('liquido_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dias_trabajados', models.IntegerField(blank=True, null=True)),
                ('dias_ausencia', models.IntegerField(default=0)),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
                ('fuente_datos', models.JSONField(default=dict, help_text='Fuentes de datos usadas para consolidar')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_consolidada', to='nomina.cierrenomina')),
            ],
            options={
                'verbose_name': 'Nómina Consolidada',
                'verbose_name_plural': 'Nóminas Consolidadas',
                'ordering': ['nombre_empleado'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Nueva Incorporación'), ('finiquito', 'Finiquito'), ('ausentismo', 'Ausencia Periodo'), ('reincorporacion', 'Reincorporación después de Ausencia'), ('cambio_datos', 'Cambio de Datos Personales')], max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=300, null=True)),
                ('dias_ausencia', models.IntegerField(blank=True, help_text='Días de ausencia si aplica', null=True)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('detectado_por_sistema', models.CharField(default='consolidacion_automatica', max_length=100)),
                ('nomina_consolidada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='nomina.nominaconsolidada')),
            ],
            options={
                'verbose_name': 'Movimiento de Personal',
                'verbose_name_plural': 'Movimientos de Personal',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_concepto', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('nombre_concepto', models.CharField(max_length=200)),
                ('tipo_concepto', models.CharField(blank=True, choices=[('haber_imponible', 'Haber Imponible'), ('haber_no_imponible', 'Haber No Imponible'), ('descuento_legal', 'Descuento Legal'), ('otro_descuento', 'Otro Descuento'), ('aporte_patronal', 'Aporte Patronal'), ('informativo', 'Solo Informativo')], max_length=20, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cantidad', models.DecimalField(decimal_places=4, default=1, help_text='Cantidad/Horas si aplica', max_digits=10)),
                ('es_numerico', models.BooleanField(default=True, help_text='Si el concepto tiene valor numérico')),
                ('fuente_archivo', models.CharField(default='consolidacion', help_text='libro/movimientos/novedades/analista', max_length=50)),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
                ('nomina_consolidada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='nomina.nominaconsolidada')),
            ],
            options={
                'verbose_name': 'Concepto Consolidado',
                'verbose_name_plural': 'Conceptos Consolidados',
                'ordering': ['-monto_total', 'nombre_concepto'],
            },
        ),
        migrations.AddIndex(
            model_name='nominaconsolidada',
            index=models.Index(fields=['cierre', 'estado_empleado'], name='nomina_nomi_cierre__8f9772_idx'),
        ),
        migrations.AddIndex(
            model_name='nominaconsolidada',
            index=models.Index(fields=['rut_empleado'], name='nomina_nomi_rut_emp_3e3383_idx'),
        ),
        migrations.AddIndex(
            model_name='nominaconsolidada',
            index=models.Index(fields=['liquido_pagar'], name='nomina_nomi_liquido_7d4a82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nominaconsolidada',
            unique_together={('cierre', 'rut_empleado')},
        ),
        migrations.AddIndex(
            model_name='movimientopersonal',
            index=models.Index(fields=['nomina_consolidada', 'tipo_movimiento'], name='nomina_movi_nomina__a36559_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientopersonal',
            index=models.Index(fields=['fecha_movimiento'], name='nomina_movi_fecha_m_8cd963_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptoconsolidado',
            index=models.Index(fields=['nomina_consolidada', 'tipo_concepto'], name='nomina_conc_nomina__3bc30f_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptoconsolidado',
            index=models.Index(fields=['nombre_concepto'], name='nomina_conc_nombre__3e51c1_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptoconsolidado',
            index=models.Index(fields=['monto_total'], name='nomina_conc_monto_t_c5adf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptoconsolidado',
            unique_together={('nomina_consolidada', 'nombre_concepto')},
        ),
    ]
