# Generated by Django 5.2.1 on 2025-07-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0029_add_consolidated_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrenomina',
            name='total_incidencias',
            field=models.PositiveIntegerField(default=0, help_text='Total de incidencias detectadas'),
        ),
    ]
