# Generated by Django 5.2.1 on 2025-07-22 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0031_alter_cierrenomina_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderValorEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_header', models.CharField(db_index=True, max_length=200)),
                ('valor_original', models.CharField(help_text='Valor tal como viene del Excel', max_length=500)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('es_numerico', models.BooleanField(default=False)),
                ('columna_excel', models.CharField(blank=True, help_text="Ej: 'D', 'AE'", max_length=10, null=True)),
                ('fila_excel', models.IntegerField(blank=True, null=True)),
                ('fuente_archivo', models.CharField(default='libro_remuneraciones', max_length=50)),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
                ('concepto_remuneracion', models.ForeignKey(blank=True, help_text='Clasificación del header si está disponible', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.conceptoremuneracion')),
                ('nomina_consolidada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_valores', to='nomina.nominaconsolidada')),
            ],
            options={
                'verbose_name': 'Header-Valor por Empleado',
                'verbose_name_plural': 'Headers-Valores por Empleado',
                'ordering': ['nombre_header'],
                'indexes': [models.Index(fields=['nomina_consolidada', 'nombre_header'], name='nomina_head_nomina__b39135_idx'), models.Index(fields=['nombre_header'], name='nomina_head_nombre__4551a6_idx'), models.Index(fields=['valor_numerico'], name='nomina_head_valor_n_81719e_idx'), models.Index(fields=['es_numerico'], name='nomina_head_es_nume_22bb46_idx')],
                'unique_together': {('nomina_consolidada', 'nombre_header')},
            },
        ),
    ]
