# Generated by Django 5.2.1 on 2025-07-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0032_headervalorempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrenomina',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cargando_archivos', 'Cargando Archivos'), ('archivos_completos', 'Archivos Completos'), ('verificacion_datos', 'Verificación de Datos'), ('verificado_sin_discrepancias', 'Verificado Sin Discrepancias'), ('datos_consolidados', 'Datos Consolidados'), ('con_discrepancias', 'Con Discrepancias'), ('incidencias_resueltas', 'Incidencias Resueltas'), ('validacion_final', 'Validación Final'), ('finalizado', 'Finalizado'), ('completado', 'Completado')], default='pendiente', max_length=40),
        ),
    ]
