# Generated by Django 5.2.1 on 2025-07-23 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0033_alter_cierrenomina_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrenomina',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se finalizó el cierre', null=True),
        ),
        migrations.AddField(
            model_name='cierrenomina',
            name='usuario_finalizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que finalizó el cierre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_finalizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
