# Generated by Django 5.2.1 on 2025-07-23 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0034_cierrenomina_fecha_finalizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrenomina',
            name='fecha_solicitud_recarga',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se solicitó la recarga', null=True),
        ),
        migrations.AddField(
            model_name='cierrenomina',
            name='observaciones_recarga',
            field=models.TextField(blank=True, help_text='Motivo para solicitar recarga de archivos', null=True),
        ),
        migrations.AddField(
            model_name='cierrenomina',
            name='version_datos',
            field=models.PositiveIntegerField(default=1, help_text='Versión de los datos consolidados (incrementa con cada recarga)'),
        ),
        migrations.AddField(
            model_name='resolucionincidencia',
            name='comentario_supervisor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resolucionincidencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta_analista', 'Resuelta por Analista'), ('aprobada_supervisor', 'Aprobada por Supervisor'), ('rechazada_supervisor', 'Rechazada por Supervisor')], default='pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='resolucionincidencia',
            name='fecha_supervision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolucionincidencia',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resoluciones_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cierrenomina',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cargando_archivos', 'Cargando Archivos'), ('archivos_completos', 'Archivos Completos'), ('verificacion_datos', 'Verificación de Datos'), ('verificado_sin_discrepancias', 'Verificado Sin Discrepancias'), ('datos_consolidados', 'Datos Consolidados'), ('con_discrepancias', 'Con Discrepancias'), ('con_incidencias', 'Con Incidencias'), ('incidencias_resueltas', 'Incidencias Resueltas'), ('requiere_recarga_archivos', 'Requiere Recarga de Archivos'), ('validacion_final', 'Validación Final'), ('finalizado', 'Finalizado')], default='pendiente', max_length=40),
        ),
    ]
