# Generated by Django 5.2.1 on 2025-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0035_cierrenomina_fecha_solicitud_recarga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucionincidencia',
            name='comentario_supervisor',
        ),
        migrations.RemoveField(
            model_name='resolucionincidencia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='resolucionincidencia',
            name='estado_anterior',
        ),
        migrations.RemoveField(
            model_name='resolucionincidencia',
            name='estado_nuevo',
        ),
        migrations.RemoveField(
            model_name='resolucionincidencia',
            name='fecha_supervision',
        ),
        migrations.RemoveField(
            model_name='resolucionincidencia',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='resolucionincidencia',
            name='usuarios_mencionados',
        ),
        migrations.AlterField(
            model_name='resolucionincidencia',
            name='tipo_resolucion',
            field=models.CharField(choices=[('justificacion_analista', 'Justificación del Analista'), ('correccion_analista', 'Corrección del Analista'), ('consulta_analista', 'Consulta del Analista'), ('aprobacion_supervisor', 'Aprobación del Supervisor'), ('rechazo_supervisor', 'Rechazo del Supervisor'), ('solicitud_cambio_supervisor', 'Solicitud de Cambio del Supervisor')], max_length=30),
        ),
    ]
