# Generated by Django 5.2.1 on 2025-07-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0036_remove_resolucionincidencia_comentario_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolucionincidencia',
            name='tipo_resolucion',
            field=models.CharField(choices=[('justificacion', 'Justificación del Analista'), ('consulta', 'Consulta del Supervisor'), ('rechazo', 'Rechazo del Supervisor'), ('aprobacion', 'Aprobación del Supervisor')], max_length=30),
        ),
    ]
