# Generated by Django 5.2.1 on 2025-07-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0037_alter_resolucionincidencia_tipo_resolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucionincidencia',
            name='campo_corregido',
        ),
        migrations.RemoveField(
            model_name='resolucionincidencia',
            name='valor_corregido',
        ),
    ]
