# Generated by Django 5.2.1 on 2025-09-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0241_movimiento_personal_normalizacion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nominaconsolidada',
            name='nomina_nomi_liquido_7d4a82_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientopersonal',
            new_name='nomina_movi_categor_a43ef8_idx',
            old_name='nomina_movi_categoria_subtipo_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientopersonal',
            new_name='nomina_movi_fecha_i_d4deab_idx',
            old_name='nomina_movi_fecha_inicio_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientopersonal',
            new_name='nomina_movi_hash_ev_524b3f_idx',
            old_name='nomina_movi_hash_evento_idx',
        ),
        migrations.AlterField(
            model_name='conceptoconsolidado',
            name='tipo_concepto',
            field=models.CharField(blank=True, choices=[('haber_imponible', 'Haber Imponible'), ('haber_no_imponible', 'Haber No Imponible'), ('descuento_legal', 'Descuento Legal'), ('otro_descuento', 'Otro Descuento'), ('aporte_patronal', 'Aporte Patronal'), ('impuesto', 'Impuesto'), ('informativo', 'Solo Informativo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimientopersonal',
            name='dias_ausencia',
            field=models.IntegerField(blank=True, help_text='Días de ausencia (legacy, evento completo)', null=True),
        ),
        migrations.AlterField(
            model_name='movimientopersonal',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('finiquito', 'Finiquito'), ('ausentismo', 'Ausencia'), ('reincorporacion', 'Reincorporación'), ('cambio_datos', 'Cambio de Datos'), ('cambio_contrato', 'Cambio de Contrato'), ('cambio_sueldo', 'Cambio de Sueldo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nominaconsolidada',
            name='horas_extras_cantidad',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cantidad de horas extra', max_digits=10),
        ),
    ]
