# Generated by Django 5.2.1 on 2025-09-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0243_merge_0242_conflicts'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movimientopersonal',
            name='nomina_movi_nomina__a36559_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientopersonal',
            name='nomina_movi_fecha_m_8cd963_idx',
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='tipo_incidencia',
            field=models.CharField(choices=[('variacion_concepto', 'Variación de Concepto (>30%)'), ('concepto_nuevo', 'Concepto Nuevo'), ('concepto_perdido', 'Concepto Perdido'), ('empleado_deberia_ingresar', 'Empleado que Debería Ingresar'), ('empleado_no_deberia_estar', 'Empleado que No Debería Estar'), ('ausentismo_continuo', 'Ausentismo Continuo'), ('variacion_concepto_individual', 'Variación Individual en Concepto'), ('concepto_nuevo_empleado', 'Concepto Nuevo para Empleado'), ('concepto_eliminado_empleado', 'Concepto Eliminado de Empleado'), ('empleado_nuevo', 'Empleado Nuevo sin Período Anterior'), ('variacion_suma_total', 'Variación en Suma Total de Concepto'), ('concepto_nuevo_periodo', 'Concepto Nuevo en Período'), ('concepto_eliminado_periodo', 'Concepto Eliminado del Período'), ('finiquito_no_aplicado', 'Finiquito no aplicado'), ('ingreso_no_informado', 'Ingreso no informado'), ('ingreso_empleado', 'Ingreso de empleado (Informativo)'), ('regla_negocio_violada', 'Violación de Regla de Negocio'), ('calculo_incorrecto', 'Error en Cálculo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientopersonal',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción textual directa del origen / motivo humano', max_length=300, null=True),
        ),
        migrations.AddIndex(
            model_name='movimientopersonal',
            index=models.Index(fields=['nomina_consolidada', 'categoria'], name='nomina_movi_nomina__532931_idx'),
        ),
    ]
