# Generated by Django 5.2.1 on 2025-09-15 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0244_remove_movimientopersonal_nomina_movi_nomina__a36559_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciacierre',
            name='firma_clave',
            field=models.CharField(blank=True, help_text='Clave legible de firma: ej. por_item_total|<item>|- o por_empleado_item|<item>|<rut>', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='firma_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash SHA1 hex de la firma_clave para búsquedas rápidas', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='version_detectada_primera',
            field=models.PositiveIntegerField(blank=True, help_text='Primera versión de datos (cierre.version_datos) donde apareció la incidencia', null=True),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='version_detectada_ultima',
            field=models.PositiveIntegerField(blank=True, help_text='Última versión de datos donde fue recalculada/detectada', null=True),
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Resolución'), ('resuelta_analista', 'Resuelta por Analista'), ('aprobada_supervisor', 'Aprobada por Supervisor'), ('rechazada_supervisor', 'Rechazada por Supervisor'), ('re_resuelta', 'Re-resuelta por Analista'), ('resolucion_supervisor_pendiente', 'Resolución de Supervisor Pendiente')], default='pendiente', max_length=40),
        ),
        migrations.AddIndex(
            model_name='incidenciacierre',
            index=models.Index(fields=['cierre', 'firma_hash'], name='nomina_inci_cierre__d6a994_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenciacierre',
            index=models.Index(fields=['firma_clave'], name='nomina_inci_firma_c_85377f_idx'),
        ),
    ]
