# Generated by Django 5.2.1 on 2025-09-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0245_incidenciacierre_firma_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrenomina',
            name='fecha_aprobacion_recarga',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando el supervisor aprobó la recarga', null=True),
        ),
        migrations.AlterField(
            model_name='cierrenomina',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cargando_archivos', 'Cargando Archivos'), ('archivos_completos', 'Archivos Completos'), ('verificacion_datos', 'Verificación de Datos'), ('verificado_sin_discrepancias', 'Verificado Sin Discrepancias'), ('datos_consolidados', 'Datos Consolidados'), ('con_discrepancias', 'Con Discrepancias'), ('con_incidencias', 'Con Incidencias'), ('incidencias_resueltas', 'Incidencias Resueltas'), ('recarga_solicitud_pendiente', 'Recarga Solicitada (Pendiente de Aprobación)'), ('requiere_recarga_archivos', 'Requiere Recarga de Archivos'), ('validacion_final', 'Validación Final'), ('finalizado', 'Finalizado')], default='pendiente', max_length=40),
        ),
    ]
