# Generated by Django 5.2.1 on 2025-09-22 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0246_cierrenomina_fecha_aprobacion_recarga_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='incidenciacierre',
            name='nomina_inci_rut_emp_d5e509_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidenciacierre',
            name='nomina_inci_tipo_co_4cec8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidenciacierre',
            name='nomina_inci_cierre__d6a994_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidenciacierre',
            name='nomina_inci_firma_c_85377f_idx',
        ),
        migrations.RemoveField(
            model_name='incidenciacierre',
            name='empleado_libro',
        ),
        migrations.RemoveField(
            model_name='incidenciacierre',
            name='empleado_nombre',
        ),
        migrations.RemoveField(
            model_name='incidenciacierre',
            name='empleado_novedades',
        ),
        migrations.RemoveField(
            model_name='incidenciacierre',
            name='firma_clave',
        ),
        migrations.RemoveField(
            model_name='incidenciacierre',
            name='firma_hash',
        ),
        migrations.RemoveField(
            model_name='incidenciacierre',
            name='rut_empleado',
        ),
        migrations.RemoveField(
            model_name='incidenciacierre',
            name='valor_analista',
        ),
        migrations.RemoveField(
            model_name='incidenciacierre',
            name='valor_libro',
        ),
        migrations.RemoveField(
            model_name='incidenciacierre',
            name='valor_movimientos',
        ),
        migrations.RemoveField(
            model_name='incidenciacierre',
            name='valor_novedades',
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='clasificacion_concepto',
            field=models.CharField(blank=True, help_text='Clasificación del concepto (haberes_imponibles, descuentos_legales, etc.)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='comentario_supervisor',
            field=models.TextField(blank=True, help_text='Comentario del supervisor (aprobación/rechazo)'),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='fecha_resolucion_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='hash_deteccion',
            field=models.CharField(blank=True, db_index=True, help_text='Hash único para evitar duplicados en re-detecciones', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='incidenciacierre',
            name='supervisor_revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='comentario_resolucion',
            field=models.TextField(blank=True, help_text='Justificación del analista'),
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='concepto_afectado',
            field=models.CharField(db_index=True, default='concepto_sin_especificar', help_text='Nombre del concepto que presenta la incidencia', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='datos_adicionales',
            field=models.JSONField(default=dict, help_text='Datos de variación: monto_actual, monto_anterior, delta_abs, delta_pct, etc.'),
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='descripcion',
            field=models.TextField(help_text='Descripción automática de la incidencia'),
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Análisis'), ('resuelta_analista', 'Justificada por Analista'), ('aprobada_supervisor', 'Aprobada por Supervisor'), ('rechazada_supervisor', 'Rechazada por Supervisor')], default='pendiente', max_length=40),
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='tipo_comparacion',
            field=models.CharField(choices=[('suma_total', 'Comparación Suma Total (Agregada)'), ('legacy', 'Sistema Legacy (Compatibilidad)')], default='suma_total', help_text='Tipo de análisis que detectó esta incidencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidenciacierre',
            name='tipo_incidencia',
            field=models.CharField(choices=[('variacion_suma_total', 'Variación en Suma Total de Concepto (≥30%)'), ('concepto_nuevo_periodo', 'Concepto Nuevo en Período'), ('concepto_eliminado_periodo', 'Concepto Eliminado del Período')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='incidenciacierre',
            index=models.Index(fields=['concepto_afectado'], name='nomina_inci_concept_104130_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenciacierre',
            index=models.Index(fields=['hash_deteccion'], name='nomina_inci_hash_de_8ac210_idx'),
        ),
        migrations.AddConstraint(
            model_name='incidenciacierre',
            constraint=models.UniqueConstraint(fields=('cierre', 'concepto_afectado', 'tipo_incidencia'), name='unique_incidencia_por_concepto_cierre'),
        ),
    ]
