# Generated by Django 5.2.1 on 2025-09-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0247_remove_incidenciacierre_nomina_inci_rut_emp_d5e509_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analistaincidencia',
            name='fecha_fin_ausencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoausentismo',
            name='fecha_fin_ausencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
