# Generated by Django 5.2.1 on 2025-10-13 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20250717_2256'),
        ('nomina', '0247_remove_incidenciacierre_nomina_inci_rut_emp_d5e509_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, help_text='Tipo de evento: upload, process, view, etc.', max_length=50)),
                ('resource_type', models.CharField(db_index=True, help_text='Tipo de recurso: nomina, contabilidad, etc.', max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID del recurso específico', max_length=100)),
                ('action', models.CharField(help_text='Acción específica realizada', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detalles adicionales del evento')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='ID de sesión para agrupar eventos relacionados', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nomina_activity_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='nomina_acti_timesta_37965b_idx'), models.Index(fields=['user', 'timestamp'], name='nomina_acti_user_id_bff2e2_idx'), models.Index(fields=['cliente', 'timestamp'], name='nomina_acti_cliente_0f04dc_idx'), models.Index(fields=['event_type', 'timestamp'], name='nomina_acti_event_t_8117d0_idx'), models.Index(fields=['resource_type', 'resource_id'], name='nomina_acti_resourc_b2d9e1_idx'), models.Index(fields=['session_id'], name='nomina_acti_session_38405d_idx')],
            },
        ),
    ]
