# Generated by Django 5.2.1 on 2025-10-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0248_add_activity_event_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='resource_id',
            field=models.CharField(blank=True, help_text='ID del recurso específico (puede contener nombres de archivo largos)', max_length=255),
        ),
    ]
