# Generated by Django 5.2.1 on 2025-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0249_alter_activityevent_resource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='action',
            field=models.CharField(help_text='Acción específica realizada (aumentado para nombres largos)', max_length=255),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de sesión para agrupar eventos relacionados (UUID largo)', max_length=255),
        ),
    ]
