# Generated by Django 5.2.1 on 2025-10-17 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20250717_2256'),
        ('nomina', '0250_alter_activityevent_action_sessionid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='cierre',
            field=models.ForeignKey(blank=True, help_text='Cierre de nómina relacionado (normalizado para queries eficientes)', null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.cierrenomina'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['cierre', 'timestamp'], name='nomina_acti_cierre__694dd0_idx'),
        ),
    ]
