# Generated by Django 5.2.1 on 2025-10-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0251_add_cierre_to_activity_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepanciacierre',
            name='tipo_discrepancia',
            field=models.CharField(choices=[('empleado_solo_libro', 'Empleado solo en Libro'), ('empleado_solo_novedades', 'Empleado solo en Novedades'), ('diff_datos_personales', 'Diferencia en Datos Personales'), ('diff_sueldo_base', 'Diferencia en Sueldo Base'), ('diff_concepto_monto', 'Diferencia en Monto por Concepto'), ('concepto_solo_libro', 'Concepto solo en Libro'), ('concepto_solo_novedades', 'Concepto solo en Novedades'), ('ingreso_no_reportado', 'Ingreso no reportado por Analista'), ('finiquito_no_reportado', 'Finiquito no reportado por Analista'), ('ausencia_no_reportada', 'Ausencia no reportada por Analista'), ('ausencia_no_en_movimientos', 'Ausencia reportada por Analista no encontrada en Movimientos'), ('diff_fechas_ausencia', 'Diferencia en Fechas de Ausencia'), ('diff_dias_ausencia', 'Diferencia en Días de Ausencia'), ('diff_tipo_ausencia', 'Diferencia en Tipo de Ausencia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tarjetaactivitylognomina',
            name='tarjeta',
            field=models.CharField(choices=[('libro_remuneraciones', 'Tarjeta: Libro de Remuneraciones'), ('movimientos_mes', 'Tarjeta: Movimientos del Mes'), ('novedades', 'Tarjeta: Novedades'), ('archivos_analista', 'Tarjeta: Archivos del Analista'), ('analista_finiquitos', 'Tarjeta: Finiquitos'), ('analista_incidencias', 'Tarjeta: Incidencias/Ausentismos'), ('analista_ingresos', 'Tarjeta: Nuevos Ingresos'), ('incidencias', 'Tarjeta: Incidencias'), ('revision', 'Tarjeta: Revisión')], max_length=25),
        ),
    ]
