# Generated by Django 5.2.1 on 2025-05-12 18:18

import contabilidad.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_remove_servicio_area_servicio_servicio_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('fecha_inicio_libro', models.DateField()),
                ('fecha_fin_libro', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('clasificacion', 'Esperando Clasificación'), ('incidencias', 'Incidencias Abiertas'), ('en_revision', 'En Revisión'), ('rechazado', 'Rechazado'), ('aprobado', 'Aprobado'), ('completo', 'Completo')], max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cliente', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='ClasificacionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ClasificacionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('set_clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='contabilidad.clasificacionset')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='AperturaCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cierremensual')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('formato', 'Formato'), ('negocio', 'Negocio')], max_length=50)),
                ('descripcion', models.TextField()),
                ('respuesta', models.TextField(blank=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cierremensual')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('respondida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibroMayorUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=contabilidad.models.libro_upload_path)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('errores', models.TextField(blank=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='contabilidad.cierremensual')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('numero_comprobante', models.CharField(blank=True, max_length=50)),
                ('numero_interno', models.CharField(blank=True, max_length=50)),
                ('centro_costo', models.CharField(blank=True, max_length=100)),
                ('auxiliar', models.CharField(blank=True, max_length=50)),
                ('detalle_gasto', models.TextField(blank=True)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('descripcion', models.TextField(blank=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cierremensual')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuentacontable')),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='AccountClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.clasificacionoption')),
                ('set_clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.clasificacionset')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='contabilidad.cuentacontable')),
            ],
            options={
                'unique_together': {('cuenta', 'set_clas')},
            },
        ),
    ]
