# Generated by Django 5.2.1 on 2025-05-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_tipodocumentoarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromayorupload',
            name='estado',
            field=models.CharField(choices=[('subido', 'Archivo subido'), ('procesando', 'Procesando'), ('completado', 'Procesado correctamente'), ('error', 'Con errores')], default='subido', max_length=20),
        ),
    ]
