# Generated by Django 5.2.1 on 2025-05-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_cierremensual_fecha_fin_libro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierremensual',
            name='cuentas_nuevas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierremensual',
            name='parsing_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cierremensual',
            name='resumen_parsing',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
