# Generated by Django 5.2.1 on 2025-05-27 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('contabilidad', '0008_cuentacontable_nombre_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierremensual',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.area'),
        ),
    ]
