# Generated by Django 5.2.1 on 2025-05-28 21:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('contabilidad', '0009_cierremensual_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CierreMensual',
            new_name='CierreContabilidad',
        ),
    ]
