# Generated by Django 5.2.1 on 2025-06-12 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('contabilidad', '0012_bulkclasificacionupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombresEnInglesUpload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='nombres_ingles/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('subido', 'Archivo subido'), ('procesando', 'Procesando'), ('completado', 'Procesado correctamente'), ('error', 'Con errores')], default='subido', max_length=20)),
                ('errores', models.TextField(blank=True)),
                ('resumen', models.JSONField(blank=True, null=True)),
                ('cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cierrecontabilidad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'verbose_name': 'Upload de Nombres en Inglés',
                'verbose_name_plural': 'Uploads de Nombres en Inglés',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
