# Generated by Django 5.2.1 on 2025-06-13 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('contabilidad', '0016_delete_uploadchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionCuentaArchivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('clasificaciones', models.JSONField()),
                ('fila_excel', models.IntegerField(blank=True, null=True)),
                ('procesado', models.BooleanField(default=False)),
                ('errores_mapeo', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('cuenta_mapeada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_archivo', to='contabilidad.cuentacontable')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_archivo', to='contabilidad.bulkclasificacionupload')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'procesado'], name='contabilida_cliente_0e6fb5_idx'), models.Index(fields=['upload', 'procesado'], name='contabilida_upload__5b9df0_idx')],
                'unique_together': {('upload', 'numero_cuenta')},
            },
        ),
    ]
