# Generated by Django 5.2.1 on 2025-06-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_nombreseninglesarchivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NombresEnInglesArchivo',
        ),
    ]
