# Generated by Django 5.2.1 on 2025-06-17 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('contabilidad', '0020_nombreinglesarchivo_nombreingles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_upload', models.CharField(choices=[('tipo_documento', 'Tipo de Documento'), ('clasificacion', 'Clasificación Bulk'), ('nombres_ingles', 'Nombres en Inglés'), ('libro_mayor', 'Libro Mayor')], max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('tamaño_archivo', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('hash_archivo', models.CharField(blank=True, help_text='SHA-256 del archivo', max_length=64)),
                ('estado', models.CharField(choices=[('subido', 'Archivo subido'), ('procesando', 'Procesando'), ('completado', 'Procesado correctamente'), ('error', 'Con errores')], default='subido', max_length=20)),
                ('errores', models.TextField(blank=True)),
                ('resumen', models.JSONField(blank=True, null=True)),
                ('tiempo_procesamiento', models.DurationField(blank=True, null=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cierrecontabilidad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Upload',
                'verbose_name_plural': 'Logs de Uploads',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddField(
            model_name='tipodocumentoarchivo',
            name='upload_log',
            field=models.ForeignKey(blank=True, help_text='Referencia al log del upload que generó este archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.uploadlog'),
        ),
        migrations.AddIndex(
            model_name='uploadlog',
            index=models.Index(fields=['cliente', 'tipo_upload'], name='contabilida_cliente_99ecac_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadlog',
            index=models.Index(fields=['estado', 'fecha_subida'], name='contabilida_estado_6af07e_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadlog',
            index=models.Index(fields=['tipo_upload', 'estado'], name='contabilida_tipo_up_5c2169_idx'),
        ),
    ]
