# Generated by Django 5.2.1 on 2025-06-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0025_libromayorupload_uploadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetaactivitylog',
            name='tarjeta',
            field=models.CharField(choices=[('tipo_documento', 'Tarjeta: Tipo de Documento'), ('libro_mayor', 'Tarjeta: Libro Mayor'), ('clasificacion', 'Tarjeta: Clasificaciones'), ('nombres_ingles', 'Tarjeta: Nombres en Inglés'), ('incidencias', 'Tarjeta: Incidencias'), ('revision', 'Tarjeta: Revisión')], max_length=20),
        ),
    ]
