# Generated by Django 5.2.1 on 2025-06-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0027_merge_20250624_1756'),
        ('contabilidad', '0027_movimientocontable_tipo_doc_codigo'),
    ]

    operations = [
    ]
