# Generated by Django 5.2.1 on 2025-06-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0028_merge_20250624_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromayorupload',
            name='incidencias_detectadas',
            field=models.IntegerField(default=0, help_text='Número de incidencias detectadas durante el procesamiento'),
        ),
        migrations.AddField(
            model_name='libromayorupload',
            name='movimientos_procesados',
            field=models.IntegerField(default=0, help_text='Número de movimientos contables creados'),
        ),
        migrations.AddField(
            model_name='libromayorupload',
            name='resumen_procesamiento',
            field=models.JSONField(blank=True, help_text='Resumen detallado del procesamiento', null=True),
        ),
    ]
