# Generated by Django 5.2.1 on 2025-06-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0030_remove_libromayorupload_incidencias_detectadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacioncuentaarchivo',
            name='upload_log',
            field=models.ForeignKey(blank=True, help_text='Referencia al log del upload que generó este archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_archivo', to='contabilidad.uploadlog'),
        ),
    ]
