# Generated by Django 5.2.1 on 2025-06-25 16:42

import contabilidad.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('contabilidad', '0031_alter_clasificacioncuentaarchivo_upload_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libromayorupload',
            options={'verbose_name': 'Libro Mayor Upload (Legacy)', 'verbose_name_plural': 'Libro Mayor Uploads (Legacy)'},
        ),
        migrations.AlterField(
            model_name='libromayorupload',
            name='archivo',
            field=models.FileField(upload_to='libros/legacy/'),
        ),
        migrations.CreateModel(
            name='LibroMayorArchivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to=contabilidad.models.libro_upload_path)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.CharField(help_text='Período MMAAAA extraído del nombre del archivo (ej: 042025)', max_length=6)),
                ('procesado', models.BooleanField(default=False)),
                ('errores', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('subido', 'Archivo subido'), ('procesando', 'Procesando'), ('completado', 'Procesado correctamente'), ('error', 'Con errores')], default='subido', max_length=20)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('upload_log', models.ForeignKey(blank=True, help_text='Referencia al log del upload que generó este archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.uploadlog')),
            ],
            options={
                'verbose_name': 'Archivo de Libro Mayor',
                'verbose_name_plural': 'Archivos de Libro Mayor',
            },
        ),
    ]
