# Generated by Django 5.2.1 on 2025-06-26 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_bilingue'),
        ('contabilidad', '0032_alter_libromayorupload_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcepcionValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_excepcion', models.CharField(choices=[('tipos_doc_no_reconocidos', 'Tipo de Documento No Aplica'), ('movimientos_tipodoc_nulo', 'Tipo de Documento No Requerido'), ('cuentas_sin_nombre_ingles', 'Nombre en Inglés No Aplica'), ('cuentas_sin_clasificacion', 'Clasificación No Aplica')], max_length=50)),
                ('codigo_cuenta', models.CharField(max_length=20)),
                ('nombre_cuenta', models.CharField(blank=True, max_length=200)),
                ('motivo', models.TextField(blank=True, help_text='Motivo por el cual no aplica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('usuario_creador', models.ForeignKey(help_text='Usuario que creó la excepción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excepción de Validación',
                'verbose_name_plural': 'Excepciones de Validación',
                'indexes': [models.Index(fields=['cliente', 'tipo_excepcion', 'activa'], name='contabilida_cliente_c6cdcf_idx'), models.Index(fields=['codigo_cuenta'], name='contabilida_codigo__f8de7f_idx')],
                'unique_together': {('cliente', 'tipo_excepcion', 'codigo_cuenta')},
            },
        ),
    ]
