# Generated by Django 5.2.1 on 2025-06-30 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_supervisor_relation'),
        ('contabilidad', '0033_excepcionvalidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromayorarchivo',
            name='cierre',
            field=models.OneToOneField(blank=True, help_text='Cierre contable al que pertenece este libro mayor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libro_mayor_archivo', to='contabilidad.cierrecontabilidad'),
        ),
        migrations.AlterField(
            model_name='libromayorarchivo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
        migrations.AddConstraint(
            model_name='libromayorarchivo',
            constraint=models.UniqueConstraint(fields=('cliente', 'cierre'), name='unique_libro_mayor_por_cierre'),
        ),
    ]
