# Generated by Django 5.2.1 on 2025-06-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0034_libromayorarchivo_cierre_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='libromayorarchivo',
            name='unique_libro_mayor_por_cierre',
        ),
        migrations.AlterField(
            model_name='libromayorarchivo',
            name='cierre',
            field=models.OneToOneField(help_text='Cierre contable al que pertenece este libro mayor', on_delete=django.db.models.deletion.CASCADE, related_name='libro_mayor_archivo', to='contabilidad.cierrecontabilidad'),
        ),
    ]
