# Generated by Django 5.2.1 on 2025-07-01 00:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0035_remove_libromayorarchivo_unique_libro_mayor_por_cierre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historialreprocesamiento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='historialreprocesamiento',
            name='upload_log',
        ),
        migrations.RemoveField(
            model_name='historialreprocesamiento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='libromayorupload',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='libromayorupload',
            name='upload_log',
        ),
        migrations.RemoveField(
            model_name='logresolucionincidencia',
            name='incidencia_resumen',
        ),
        migrations.RemoveField(
            model_name='logresolucionincidencia',
            name='upload_log_relacionado',
        ),
        migrations.RemoveField(
            model_name='logresolucionincidencia',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ['tipo', 'cuenta_codigo', 'tipo_doc_codigo', 'fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='incidenciaresumen',
            options={'ordering': ['-fecha_deteccion'], 'verbose_name': 'Resumen de Incidencia'},
        ),
        migrations.RemoveIndex(
            model_name='incidenciaresumen',
            name='contabilida_upload__4c371f_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidenciaresumen',
            name='contabilida_upload__dc247e_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidenciaresumen',
            name='contabilida_severid_7f5e2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidenciaresumen',
            name='contabilida_fecha_d_20650b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='incidenciaresumen',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='respondida_por',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='resuelta',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='cuenta_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Cuenta'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo_doc_codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Doc.'),
        ),
        migrations.AddField(
            model_name='incidenciaresumen',
            name='cierre',
            field=models.ForeignKey(default=79, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cierrecontabilidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidenciaresumen',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidenciaresumen',
            name='estadisticas',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='incidenciaresumen',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('CUENTA_NO_CLAS', 'Cuenta no clasificada'), ('CUENTA_INGLES', 'Cuenta sin mapeo inglés'), ('DOC_NO_REC', 'Tipo de documento no reconocido'), ('DOC_NULL', 'Tipo de documento vacío')], max_length=16),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='cantidad_afectada',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='codigo_problema',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='detalle_muestra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='elementos_afectados',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta'), ('obsoleta', 'Obsoleta')], default='activa', max_length=8),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='fecha_deteccion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='severidad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=8),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='tipo_incidencia',
            field=models.CharField(choices=[('CUENTA_NO_CLAS', 'Cuenta no clasificada'), ('CUENTA_INGLES', 'Cuenta sin mapeo inglés'), ('DOC_NO_REC', 'Tipo de documento no reconocido'), ('DOC_NULL', 'Tipo de documento vacío')], max_length=32),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='upload_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.uploadlog'),
        ),
        migrations.DeleteModel(
            name='HistorialReprocesamiento',
        ),
        migrations.DeleteModel(
            name='LibroMayorUpload',
        ),
        migrations.DeleteModel(
            name='LogResolucionIncidencia',
        ),
        migrations.RemoveField(
            model_name='incidenciaresumen',
            name='accion_sugerida',
        ),
        migrations.RemoveField(
            model_name='incidenciaresumen',
            name='estadisticas_adicionales',
        ),
        migrations.RemoveField(
            model_name='incidenciaresumen',
            name='mensaje_usuario',
        ),
    ]
