# Generated by Django 5.2.1 on 2025-07-01 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_supervisor_relation'),
        ('contabilidad', '0038_incidenciaresumen_accion_sugerida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlog',
            name='es_iteracion_principal',
            field=models.BooleanField(default=True, help_text='Marca si es la iteración principal visible al usuario'),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='iteracion',
            field=models.PositiveIntegerField(default=1, help_text='Número de iteración de procesamiento para este cierre (1=inicial, 2+=reproceso)'),
        ),
        migrations.AddIndex(
            model_name='uploadlog',
            index=models.Index(fields=['cierre', 'tipo_upload', 'iteracion'], name='contabilida_cierre__acd99f_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadlog',
            index=models.Index(fields=['cierre', 'tipo_upload', 'es_iteracion_principal'], name='contabilida_cierre__0ab95e_idx'),
        ),
    ]
