# Generated by Django 5.2.1 on 2025-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0039_uploadlog_es_iteracion_principal_uploadlog_iteracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacionoption',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Descripción en inglés', null=True),
        ),
        migrations.AddField(
            model_name='clasificacionoption',
            name='valor_en',
            field=models.CharField(blank=True, help_text='Valor en inglés', max_length=100, null=True),
        ),
    ]
