# Generated by Django 5.2.1 on 2025-07-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0042_fix_activity_log_action_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='set_clasificacion_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Set Clasificación'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='set_clasificacion_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Set Clasificación'),
        ),
    ]
