# Generated by Django 5.2.1 on 2025-07-03 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0044_cierrecontabilidad_fecha_finalizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFinanciero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('esf', 'Estado de Situación Financiera / State of Financial Situation'), ('eri', 'Estado de Resultado Integral / Statements of Comprehensive Income'), ('ecp', 'Estado de Cambios en el Patrimonio / State of Change of Patrimony')], max_length=10)),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='generando', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('datos_reporte', models.JSONField(blank=True, help_text='Datos estructurados del reporte financiero', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre el reporte (tiempo generación, versión, etc.)')),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si la generación falló')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='contabilidad.cierrecontabilidad')),
                ('usuario_generador', models.ForeignKey(help_text='Usuario que solicitó la generación del reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Financiero',
                'verbose_name_plural': 'Reportes Financieros',
                'indexes': [models.Index(fields=['cierre', 'tipo_reporte'], name='contabilida_cierre__8a8f1e_idx'), models.Index(fields=['estado', 'fecha_generacion'], name='contabilida_estado_7177e3_idx')],
                'unique_together': {('cierre', 'tipo_reporte')},
            },
        ),
    ]
