# Generated by Django 5.2.1 on 2025-07-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0045_reportefinanciero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('CUENTA_NO_CLAS', 'Cuenta no clasificada'), ('CUENTA_INGLES', 'Cuenta sin mapeo inglés'), ('DOC_NO_REC', 'Tipo de documento no reconocido'), ('DOC_NULL', 'Tipo de documento vacío'), ('BALANCE_DESC', 'Balance ESF/ERI descuadrado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incidenciaresumen',
            name='tipo_incidencia',
            field=models.CharField(choices=[('CUENTA_NO_CLAS', 'Cuenta no clasificada'), ('CUENTA_INGLES', 'Cuenta sin mapeo inglés'), ('DOC_NO_REC', 'Tipo de documento no reconocido'), ('DOC_NULL', 'Tipo de documento vacío'), ('BALANCE_DESC', 'Balance ESF/ERI descuadrado')], max_length=32),
        ),
    ]
