# Generated by Django 5.2.1 on 2025-07-10 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_supervisor_relation'),
        ('contabilidad', '0048_remove_clasificacioncuentaarchivo_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountclassification',
            name='cuenta_or_codigo_required',
        ),
        migrations.AddConstraint(
            model_name='accountclassification',
            constraint=models.CheckConstraint(condition=models.Q(('cuenta__isnull', False), models.Q(('cuenta__isnull', True), ('cuenta_codigo__isnull', False)), _connector='OR'), name='cuenta_or_codigo_required'),
        ),
    ]
