# Generated by Django 5.2.1 on 2025-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0050_enable_bilingual_options_all_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetaactivitylog',
            name='tarjeta',
            field=models.CharField(choices=[('tipo_documento', 'Tarjeta: Tipo de Documento'), ('libro_mayor', 'Tarjeta: Libro Mayor'), ('clasificacion', 'Tarjeta: Clasificaciones'), ('nombres_ingles', 'Tarjeta: Nombres en Inglés'), ('incidencias', 'Tarjeta: Incidencias'), ('revision', 'Tarjeta: Revisión'), ('movimientos_cuenta', 'Tarjeta: Movimientos por Cuenta'), ('movimientos_resumen', 'Tarjeta: Resumen de Movimientos'), ('reportes', 'Tarjeta: Reportes')], max_length=30),
        ),
    ]
