# Generated by Django 5.2.1 on 2025-09-05 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20250717_2256'),
        ('contabilidad', '0052_accountclassification_fk_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nombreingles',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nombreingles',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='nombreingles',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='nombreinglesarchivo',
            name='cliente',
        ),
        migrations.RemoveIndex(
            model_name='accountclassification',
            name='contabilida_cliente_73dd80_idx',
        ),
        migrations.AlterField(
            model_name='accountclassification',
            name='cliente',
            field=models.ForeignKey(help_text='Se sincroniza automáticamente con cuenta.cliente', on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='accountclassification',
            name='origen',
            field=models.CharField(choices=[('excel', 'Archivo Excel'), ('manual', 'Creación Manual'), ('actualizacion', 'Actualización desde Excel')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='accountclassification',
            index=models.Index(fields=['cliente', 'set_clas'], name='contabilida_cliente_07f8a8_idx'),
        ),
        migrations.DeleteModel(
            name='NombreIngles',
        ),
        migrations.DeleteModel(
            name='NombreInglesArchivo',
        ),
    ]
