# Generated by Django 5.2.1 on 2025-09-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0054_incidencia_add_fk_cuenta'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='incidencia',
            name='incid_cuenta_idx',
        ),
    ]
