# Generated by Django 5.2.1 on 2025-08-25 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0007_merge_20250717_2256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierrePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: YYYY-MM', max_length=7)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('archivos_subidos', 'Archivos Subidos'), ('con_discrepancias', 'Con Discrepancias'), ('sin_discrepancias', 'Sin Discrepancias'), ('datos_consolidados', 'Datos Consolidados'), ('revision_analista', 'En Revisión por Analista'), ('aprobado', 'Aprobado'), ('cerrado', 'Cerrado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_payroll', to='api.cliente')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Payroll',
                'verbose_name_plural': 'Cierres de Payroll',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('cliente', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='ArchivoSubido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('libro_remuneraciones', 'Talana - Libro de Remuneraciones'), ('movimientos_mes', 'Talana - Movimientos del Mes'), ('ausentismos', 'Analista - Ausentismos'), ('ingresos', 'Analista - Ingresos'), ('finiquitos', 'Analista - Finiquitos'), ('novedades', 'Analista - Novedades')], max_length=30)),
                ('estado', models.CharField(choices=[('subido', 'Subido'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('error', 'Error'), ('validado', 'Validado')], default='subido', max_length=15)),
                ('nombre_original', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='payroll/archivos/%Y/%m/')),
                ('tamaño', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('hash_md5', models.CharField(max_length=32, unique=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('errores_detectados', models.IntegerField(default=0)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('log_errores', models.JSONField(blank=True, default=list)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='payroll.cierrepayroll')),
            ],
            options={
                'verbose_name': 'Archivo Subido',
                'verbose_name_plural': 'Archivos Subidos',
                'ordering': ['fecha_subida'],
                'unique_together': {('cierre', 'tipo_archivo')},
            },
        ),
    ]
