# Generated by Django 5.2.1 on 2025-08-14 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs_Comparacion',
            new_name='Logs_Actividad',
        ),
    ]
