# Generated by Django 5.2.1 on 2025-08-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cierrepayroll',
            old_name='fecha_cierre',
            new_name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='cierrepayroll',
            name='fecha_ultima_actualizacion',
        ),
    ]
