# Generated by Django 5.2.1 on 2025-08-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_rename_fecha_cierre_cierrepayroll_fecha_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosubido',
            name='hash_md5',
            field=models.CharField(max_length=32),
        ),
    ]
