# Generated by Django 5.2.1 on 2025-08-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_cambio_nombre_logs_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs_actividad',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log de Actividad', 'verbose_name_plural': 'Logs de Actividades'},
        ),
    ]
