# Generated by Django 5.2.1 on 2025-08-27 01:36

import payroll.models.models_fase_1
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_archivosubido_hash_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosubido',
            name='archivo',
            field=models.FileField(upload_to=payroll.models.models_fase_1.archivo_upload_path),
        ),
    ]
