# Generated by Django 5.2.1 on 2025-08-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_archivosubido_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosubido',
            name='estado_procesamiento',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parseando', 'Parseando'), ('error', 'Error'), ('parsing_completo', 'Parsing Completo')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemsRemuneraciones_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_columna', models.CharField(max_length=10)),
                ('nombre_concepto', models.CharField(max_length=200)),
                ('nombre_normalizado', models.CharField(blank=True, max_length=200)),
                ('tipo_concepto', models.CharField(blank=True, choices=[('haber', 'Haber'), ('descuento', 'Descuento'), ('informativo', 'Informativo'), ('total', 'Total')], max_length=15)),
                ('orden', models.IntegerField()),
                ('fila_header', models.IntegerField(default=1)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_remuneraciones', to='payroll.archivosubido')),
            ],
            options={
                'verbose_name': 'Items de Remuneraciones Staging',
                'verbose_name_plural': 'Items de Remuneraciones Staging',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ListaEmpleados_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('fila_excel', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_empleados', to='payroll.archivosubido')),
            ],
            options={
                'verbose_name': 'Lista de Empleados Staging',
                'verbose_name_plural': 'Listas de Empleados Staging',
            },
        ),
        migrations.CreateModel(
            name='ValorItemEmpleado_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.CharField(max_length=200)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_texto', models.CharField(blank=True, max_length=200)),
                ('fila_excel', models.IntegerField()),
                ('columna_excel', models.CharField(max_length=10)),
                ('es_numerico', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_items_empleados', to='payroll.archivosubido')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_remuneracion', to='payroll.listaempleados_stg')),
                ('item_remuneracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_empleados', to='payroll.itemsremuneraciones_stg')),
            ],
            options={
                'verbose_name': 'Valor Item Empleado Staging',
                'verbose_name_plural': 'Valores Items Empleados Staging',
            },
        ),
        migrations.AddIndex(
            model_name='itemsremuneraciones_stg',
            index=models.Index(fields=['archivo_subido', 'tipo_concepto'], name='payroll_ite_archivo_c06796_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsremuneraciones_stg',
            index=models.Index(fields=['orden'], name='payroll_ite_orden_0dcadf_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsremuneraciones_stg',
            index=models.Index(fields=['codigo_columna'], name='payroll_ite_codigo__23cbb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemsremuneraciones_stg',
            unique_together={('archivo_subido', 'codigo_columna')},
        ),
        migrations.AddIndex(
            model_name='listaempleados_stg',
            index=models.Index(fields=['archivo_subido'], name='payroll_lis_archivo_a511b6_idx'),
        ),
        migrations.AddIndex(
            model_name='listaempleados_stg',
            index=models.Index(fields=['rut_trabajador'], name='payroll_lis_rut_tra_494bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='listaempleados_stg',
            index=models.Index(fields=['fila_excel'], name='payroll_lis_fila_ex_2c44dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listaempleados_stg',
            unique_together={('archivo_subido', 'rut_trabajador')},
        ),
        migrations.AddIndex(
            model_name='valoritemempleado_stg',
            index=models.Index(fields=['archivo_subido'], name='payroll_val_archivo_fb0578_idx'),
        ),
        migrations.AddIndex(
            model_name='valoritemempleado_stg',
            index=models.Index(fields=['empleado', 'item_remuneracion'], name='payroll_val_emplead_53208b_idx'),
        ),
        migrations.AddIndex(
            model_name='valoritemempleado_stg',
            index=models.Index(fields=['fila_excel', 'columna_excel'], name='payroll_val_fila_ex_53c52c_idx'),
        ),
        migrations.AddIndex(
            model_name='valoritemempleado_stg',
            index=models.Index(fields=['es_numerico'], name='payroll_val_es_nume_828584_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valoritemempleado_stg',
            unique_together={('empleado', 'item_remuneracion')},
        ),
    ]
