# Generated by Django 5.2.1 on 2025-08-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_archivosubido_estado_procesamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsremuneraciones_stg',
            name='tipo_concepto',
            field=models.CharField(blank=True, choices=[('haber', 'Haber'), ('descuento', 'Descuento'), ('informativo', 'Informativo'), ('total', 'Total')], max_length=15, null=True),
        ),
    ]
