# Generated by Django 5.2.1 on 2025-08-27 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_itemsremuneraciones_stg_tipo_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencias_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('ausencia', models.CharField(blank=True, max_length=100)),
                ('fecha_fin_ausencia', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('tipo_de_ausentismo', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio_raw', models.CharField(blank=True, max_length=50)),
                ('fecha_fin_ausencia_raw', models.CharField(blank=True, max_length=50)),
                ('dias_raw', models.CharField(blank=True, max_length=50)),
                ('fila_excel', models.IntegerField()),
                ('tiene_errores', models.BooleanField(default=False)),
                ('errores_detectados', models.JSONField(blank=True, default=list)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias_staging', to='payroll.archivosubido')),
            ],
            options={
                'verbose_name': 'Ausencia Staging',
                'verbose_name_plural': 'Ausencias Staging',
                'indexes': [models.Index(fields=['archivo_subido'], name='payroll_aus_archivo_24b5b6_idx'), models.Index(fields=['rut'], name='payroll_aus_rut_f79ae9_idx'), models.Index(fields=['fecha_inicio'], name='payroll_aus_fecha_i_3622a3_idx'), models.Index(fields=['tipo_de_ausentismo'], name='payroll_aus_tipo_de_f773c3_idx'), models.Index(fields=['fila_excel'], name='payroll_aus_fila_ex_92398e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Finiquitos_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha_retiro_raw', models.CharField(blank=True, max_length=50)),
                ('fila_excel', models.IntegerField()),
                ('tiene_errores', models.BooleanField(default=False)),
                ('errores_detectados', models.JSONField(blank=True, default=list)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finiquitos_staging', to='payroll.archivosubido')),
            ],
            options={
                'verbose_name': 'Finiquito Staging',
                'verbose_name_plural': 'Finiquitos Staging',
                'indexes': [models.Index(fields=['archivo_subido'], name='payroll_fin_archivo_6aab3d_idx'), models.Index(fields=['rut'], name='payroll_fin_rut_b6a442_idx'), models.Index(fields=['fecha_retiro'], name='payroll_fin_fecha_r_1eb08d_idx'), models.Index(fields=['motivo'], name='payroll_fin_motivo_7be6af_idx'), models.Index(fields=['fila_excel'], name='payroll_fin_fila_ex_c6a3df_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ingresos_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_ingreso_raw', models.CharField(blank=True, max_length=50)),
                ('fila_excel', models.IntegerField()),
                ('tiene_errores', models.BooleanField(default=False)),
                ('errores_detectados', models.JSONField(blank=True, default=list)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_staging', to='payroll.archivosubido')),
            ],
            options={
                'verbose_name': 'Ingreso Staging',
                'verbose_name_plural': 'Ingresos Staging',
                'indexes': [models.Index(fields=['archivo_subido'], name='payroll_ing_archivo_7cc26d_idx'), models.Index(fields=['rut'], name='payroll_ing_rut_c8bd95_idx'), models.Index(fields=['fecha_ingreso'], name='payroll_ing_fecha_i_4fc3ab_idx'), models.Index(fields=['fila_excel'], name='payroll_ing_fila_ex_8e8108_idx')],
            },
        ),
    ]
