# Generated by Django 5.2.1 on 2025-08-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_ausencias_stg_finiquitos_stg_ingresos_stg'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltasBajas_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('centro_de_costo', models.CharField(blank=True, max_length=100)),
                ('sucursal', models.CharField(blank=True, max_length=100)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=100)),
                ('dias_trabajados', models.IntegerField(blank=True, null=True)),
                ('sueldo_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('alta_baja', models.CharField(blank=True, max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha_ingreso_raw', models.CharField(blank=True, max_length=50)),
                ('fecha_retiro_raw', models.CharField(blank=True, max_length=50)),
                ('dias_trabajados_raw', models.CharField(blank=True, max_length=50)),
                ('sueldo_base_raw', models.CharField(blank=True, max_length=50)),
                ('fila_excel', models.IntegerField()),
                ('tiene_errores', models.BooleanField(default=False)),
                ('errores_detectados', models.JSONField(blank=True, default=list)),
                ('observaciones_procesamiento', models.TextField(blank=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alta/Baja Staging',
                'verbose_name_plural': 'Altas/Bajas Staging',
            },
        ),
        migrations.RemoveField(
            model_name='finiquitos_stg',
            name='archivo_subido',
        ),
        migrations.RemoveField(
            model_name='ingresos_stg',
            name='archivo_subido',
        ),
        migrations.RemoveIndex(
            model_name='ausencias_stg',
            name='payroll_aus_fecha_i_3622a3_idx',
        ),
        migrations.RenameField(
            model_name='ausencias_stg',
            old_name='ausencia',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='ausencias_stg',
            old_name='fecha_inicio',
            new_name='fecha_inicio_ausencia',
        ),
        migrations.RenameField(
            model_name='ausencias_stg',
            old_name='fecha_inicio_raw',
            new_name='fecha_inicio_ausencia_raw',
        ),
        migrations.AddField(
            model_name='ausencias_stg',
            name='centro_de_costo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ausencias_stg',
            name='empresa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ausencias_stg',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ausencias_stg',
            name='observaciones_procesamiento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ausencias_stg',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='ausencias_stg',
            index=models.Index(fields=['fecha_inicio_ausencia'], name='payroll_aus_fecha_i_06cbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='ausencias_stg',
            index=models.Index(fields=['empresa'], name='payroll_aus_empresa_f19d39_idx'),
        ),
        migrations.AddIndex(
            model_name='ausencias_stg',
            index=models.Index(fields=['centro_de_costo'], name='payroll_aus_centro__eee7ab_idx'),
        ),
        migrations.AddField(
            model_name='altasbajas_stg',
            name='archivo_subido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altas_bajas_staging', to='payroll.archivosubido'),
        ),
        migrations.DeleteModel(
            name='Finiquitos_stg',
        ),
        migrations.DeleteModel(
            name='Ingresos_stg',
        ),
        migrations.AddIndex(
            model_name='altasbajas_stg',
            index=models.Index(fields=['archivo_subido'], name='payroll_alt_archivo_af231e_idx'),
        ),
        migrations.AddIndex(
            model_name='altasbajas_stg',
            index=models.Index(fields=['rut'], name='payroll_alt_rut_78de01_idx'),
        ),
        migrations.AddIndex(
            model_name='altasbajas_stg',
            index=models.Index(fields=['fecha_ingreso'], name='payroll_alt_fecha_i_d5c7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='altasbajas_stg',
            index=models.Index(fields=['fecha_retiro'], name='payroll_alt_fecha_r_f71b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='altasbajas_stg',
            index=models.Index(fields=['alta_baja'], name='payroll_alt_alta_ba_375358_idx'),
        ),
        migrations.AddIndex(
            model_name='altasbajas_stg',
            index=models.Index(fields=['empresa'], name='payroll_alt_empresa_c2b17b_idx'),
        ),
        migrations.AddIndex(
            model_name='altasbajas_stg',
            index=models.Index(fields=['centro_de_costo'], name='payroll_alt_centro__b24efc_idx'),
        ),
        migrations.AddIndex(
            model_name='altasbajas_stg',
            index=models.Index(fields=['fila_excel'], name='payroll_alt_fila_ex_4d05c8_idx'),
        ),
    ]
