# Generated by Django 5.2.1 on 2025-08-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_altasbajas_stg_remove_finiquitos_stg_archivo_subido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausentismos_analista_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_excel', models.IntegerField(help_text='Número de fila en el Excel')),
                ('rut', models.CharField(help_text='RUT del empleado', max_length=12)),
                ('nombre', models.CharField(help_text='Nombre completo del empleado', max_length=200)),
                ('fecha_inicio_ausencia', models.DateField(blank=True, help_text='Fecha de inicio de la ausencia', null=True)),
                ('fecha_fin_ausencia', models.DateField(blank=True, help_text='Fecha de fin de la ausencia', null=True)),
                ('dias', models.IntegerField(blank=True, help_text='Cantidad de días de ausencia', null=True)),
                ('tipo_ausentismo', models.CharField(blank=True, help_text='Tipo de ausentismo', max_length=200)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausentismos_analista', to='payroll.archivosubido')),
            ],
            options={
                'verbose_name': 'Ausentismo Analista Staging',
                'verbose_name_plural': 'Ausentismos Analista Staging',
                'indexes': [models.Index(fields=['archivo_subido'], name='payroll_aus_archivo_737473_idx'), models.Index(fields=['rut'], name='payroll_aus_rut_b6dce3_idx'), models.Index(fields=['fecha_inicio_ausencia'], name='payroll_aus_fecha_i_ccc5ee_idx'), models.Index(fields=['tipo_ausentismo'], name='payroll_aus_tipo_au_6d490c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Finiquitos_analista_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_excel', models.IntegerField(help_text='Número de fila en el Excel')),
                ('rut', models.CharField(help_text='RUT del empleado', max_length=12)),
                ('nombre', models.CharField(help_text='Nombre completo del empleado', max_length=200)),
                ('fecha_retiro', models.DateField(blank=True, help_text='Fecha de retiro', null=True)),
                ('motivo', models.CharField(blank=True, help_text='Motivo del finiquito', max_length=500)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finiquitos_analista', to='payroll.archivosubido')),
            ],
            options={
                'verbose_name': 'Finiquito Analista Staging',
                'verbose_name_plural': 'Finiquitos Analista Staging',
                'indexes': [models.Index(fields=['archivo_subido'], name='payroll_fin_archivo_1feec7_idx'), models.Index(fields=['rut'], name='payroll_fin_rut_bf5687_idx'), models.Index(fields=['fecha_retiro'], name='payroll_fin_fecha_r_0738cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ingresos_analista_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_excel', models.IntegerField(help_text='Número de fila en el Excel')),
                ('rut', models.CharField(help_text='RUT del empleado', max_length=12)),
                ('nombre', models.CharField(help_text='Nombre completo del empleado', max_length=200)),
                ('fecha_ingreso', models.DateField(blank=True, help_text='Fecha de ingreso', null=True)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_analista', to='payroll.archivosubido')),
            ],
            options={
                'verbose_name': 'Ingreso Analista Staging',
                'verbose_name_plural': 'Ingresos Analista Staging',
                'indexes': [models.Index(fields=['archivo_subido'], name='payroll_ing_archivo_11489a_idx'), models.Index(fields=['rut'], name='payroll_ing_rut_edf794_idx'), models.Index(fields=['fecha_ingreso'], name='payroll_ing_fecha_i_abb901_idx')],
            },
        ),
    ]
