# Generated by Django 5.2.1 on 2025-08-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_add_analista_staging_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados_Novedades_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(help_text='RUT limpio: 12345678-9', max_length=12)),
                ('nombre', models.CharField(help_text='Nombre del empleado', max_length=100)),
                ('apellido_paterno', models.CharField(help_text='Apellido paterno', max_length=100)),
                ('apellido_materno', models.CharField(blank=True, help_text='Apellido materno', max_length=100)),
                ('fila_excel', models.IntegerField(help_text='Número de fila en el Excel')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_novedades', to='payroll.archivosubido')),
            ],
            options={
                'verbose_name': 'Empleado Novedades Staging',
                'verbose_name_plural': 'Empleados Novedades Staging',
            },
        ),
        migrations.CreateModel(
            name='Items_Novedades_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_columna', models.CharField(help_text='Letra de columna: A, B, C, etc.', max_length=10)),
                ('nombre_concepto', models.CharField(help_text='Como viene del header', max_length=200)),
                ('nombre_normalizado', models.CharField(blank=True, help_text='Nombre procesado', max_length=200)),
                ('tipo_concepto', models.CharField(blank=True, choices=[('haber', 'Haber'), ('descuento', 'Descuento'), ('informativo', 'Informativo'), ('total', 'Total'), ('novedad', 'Novedad')], max_length=15, null=True)),
                ('orden', models.IntegerField(help_text='Orden de aparición en el Excel')),
                ('fila_header', models.IntegerField(default=1, help_text='Fila donde está el header')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_novedades', to='payroll.archivosubido')),
            ],
            options={
                'verbose_name': 'Item Novedades Staging',
                'verbose_name_plural': 'Items Novedades Staging',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Valores_item_empleado_analista_stg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.CharField(help_text='Valor tal como viene del Excel', max_length=200)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, help_text='Valor numérico convertido', max_digits=15, null=True)),
                ('valor_texto', models.CharField(blank=True, help_text='Para valores no numéricos', max_length=200)),
                ('fila_excel', models.IntegerField(help_text='Número de fila en el Excel')),
                ('columna_excel', models.CharField(help_text='Letra de columna', max_length=10)),
                ('es_numerico', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('archivo_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_novedades_analista', to='payroll.archivosubido')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_novedades', to='payroll.empleados_novedades_stg')),
                ('item_novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_empleados', to='payroll.items_novedades_stg')),
            ],
            options={
                'verbose_name': 'Valor Item Empleado Analista Staging',
                'verbose_name_plural': 'Valores Items Empleados Analista Staging',
            },
        ),
        migrations.AddIndex(
            model_name='empleados_novedades_stg',
            index=models.Index(fields=['archivo_subido'], name='payroll_emp_archivo_022817_idx'),
        ),
        migrations.AddIndex(
            model_name='empleados_novedades_stg',
            index=models.Index(fields=['rut_trabajador'], name='payroll_emp_rut_tra_41b1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='empleados_novedades_stg',
            index=models.Index(fields=['fila_excel'], name='payroll_emp_fila_ex_e3d867_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empleados_novedades_stg',
            unique_together={('archivo_subido', 'rut_trabajador')},
        ),
        migrations.AddIndex(
            model_name='items_novedades_stg',
            index=models.Index(fields=['archivo_subido', 'tipo_concepto'], name='payroll_ite_archivo_8bc319_idx'),
        ),
        migrations.AddIndex(
            model_name='items_novedades_stg',
            index=models.Index(fields=['orden'], name='payroll_ite_orden_933f89_idx'),
        ),
        migrations.AddIndex(
            model_name='items_novedades_stg',
            index=models.Index(fields=['codigo_columna'], name='payroll_ite_codigo__426bc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='items_novedades_stg',
            unique_together={('archivo_subido', 'codigo_columna')},
        ),
        migrations.AddIndex(
            model_name='valores_item_empleado_analista_stg',
            index=models.Index(fields=['archivo_subido'], name='payroll_val_archivo_db9cff_idx'),
        ),
        migrations.AddIndex(
            model_name='valores_item_empleado_analista_stg',
            index=models.Index(fields=['empleado', 'item_novedad'], name='payroll_val_emplead_6d466e_idx'),
        ),
        migrations.AddIndex(
            model_name='valores_item_empleado_analista_stg',
            index=models.Index(fields=['fila_excel', 'columna_excel'], name='payroll_val_fila_ex_e1ad8b_idx'),
        ),
        migrations.AddIndex(
            model_name='valores_item_empleado_analista_stg',
            index=models.Index(fields=['es_numerico'], name='payroll_val_es_nume_6c903b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valores_item_empleado_analista_stg',
            unique_together={('empleado', 'item_novedad')},
        ),
    ]
