# Generated by Django 5.2.1 on 2025-08-04 05:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('module', models.CharField(choices=[('nomina', 'Nómina'), ('contabilidad', 'Contabilidad'), ('api', 'API General'), ('task_manager', 'Gestión de Tareas'), ('system', 'Sistema')], max_length=50)),
                ('description', models.TextField()),
                ('default_timeout', models.IntegerField(default=3600)),
                ('default_max_retries', models.IntegerField(default=3)),
                ('estimated_duration_seconds', models.IntegerField(default=300)),
                ('typical_steps', models.JSONField(default=list, help_text='Lista de pasos típicos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_manager_template',
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('task_module', models.CharField(choices=[('nomina', 'Nómina'), ('contabilidad', 'Contabilidad'), ('api', 'API General'), ('task_manager', 'Gestión de Tareas'), ('system', 'Sistema')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Descripción amigable de la tarea')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('STARTED', 'Iniciada'), ('PROGRESS', 'En Progreso'), ('SUCCESS', 'Exitosa'), ('FAILURE', 'Fallida'), ('RETRY', 'Reintentando'), ('REVOKED', 'Cancelada')], default='PENDING', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Porcentaje 0-100')),
                ('current_step', models.CharField(blank=True, max_length=500)),
                ('total_steps', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_data', models.JSONField(default=dict, help_text='Datos de contexto')),
                ('result_data', models.JSONField(default=dict, help_text='Resultado exitoso')),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('timeout_seconds', models.IntegerField(default=3600)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('worker_name', models.CharField(blank=True, max_length=255)),
                ('queue_name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_manager_execution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('progress', 'Progreso')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='task_manager.taskexecution')),
            ],
            options={
                'db_table': 'task_manager_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['task_id'], name='task_manage_task_id_51eda7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['status'], name='task_manage_status_ca4b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['task_module', '-created_at'], name='task_manage_task_mo_a7e105_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['user', '-created_at'], name='task_manage_user_id_0805b7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['created_at'], name='task_manage_created_ee3431_idx'),
        ),
    ]
